import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase, ref, get, set, remove, onValue, onChildAdded, onDisconnect, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";

"use strict";
const firebaseConfig={apiKey:"AIzaSyBWRTufmXZpw5oMjw6Q7LGuBfm-F_TORgY",authDomain:"draft-duel-832d7.firebaseapp.com",databaseURL:"https://draft-duel-832d7-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"draft-duel-832d7",storageBucket:"draft-duel-832d7.firebasestorage.app",messagingSenderId:"980217895202",appId:"1:980217895202:web:866eb7a7b64ec515512d7b",measurementId:"G-3ZX24EZ405"};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getDatabase(firebaseApp);
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const screens=$$('.screen'); let role='local',myId=null,currentRoomCode='',authPromise=null,onlineUnsubs=[];
let state=null, localNames=[]; const gameSeeds=['The Legend of Zelda: Breath of the Wild','Minecraft','Mario Kart 8 Deluxe','God of War','Fortnite','Grand Theft Auto V','Elden Ring','Red Dead Redemption 2','Super Mario Odyssey','The Last of Us','Rocket League','Hades'];
function show(id){screens.forEach(x=>x.classList.toggle('hidden',x.id!==id));scrollTo(0,0)}
const pageToScreen={home:'home',local:'localSetup',host:'hostSetup',join:'join'};
function urlFor(page,room=''){const u=new URL(location.href);u.search='';u.hash='';if(page!=='home')u.searchParams.set('page',page);if(room)u.searchParams.set('room',room);return u}
function navigate(page,replace=false){const screen=pageToScreen[page]||'home',u=urlFor(page);history[replace?'replaceState':'pushState']({},'',u);show(screen);if(page==='join'){const code=new URL(location.href).searchParams.get('room');if(code)$('#joinCode').value=code.toUpperCase()}}
function routeFromUrl(){const u=new URL(location.href),room=u.searchParams.get('room')||'',page=u.searchParams.get('page')||'home';if(page==='join'&&room)$('#joinCode').value=room.toUpperCase();show(pageToScreen[page]||'home')}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(({localSetup:'local',hostSetup:'host'}[b.dataset.nav]||b.dataset.nav)));
addEventListener('popstate',routeFromUrl);routeFromUrl();
$('#howButton').onclick=()=>$('#howDialog').showModal();$('#closeHow').onclick=()=>$('#howDialog').close();
function inviteUrl(code){return urlFor('join',code).href}
$('#copyInvite').onclick=async()=>{const link=inviteUrl(currentRoomCode);try{await navigator.clipboard.writeText(link)}catch{const input=$('#inviteLink');input.focus();input.select();document.execCommand('copy')}$('#copyStatus').textContent='Invite link copied!';setTimeout(()=>$('#copyStatus').textContent='',2500)};
function setupForm(target,local){const f=$('#setupTemplate').content.cloneNode(true),root=f.querySelector('.setup'),pf=root.querySelector('.playerFields'),artists=root.querySelector('.artists');addArtist(artists,'Bruno Mars');root.querySelector('.addArtist').onclick=()=>{if(artists.children.length<8)addArtist(artists,'')};root.querySelector('.poolButton').onclick=()=>previewSongPool(root);if(local){pf.innerHTML='<h3>Players</h3><div class="names"></div><button type="button" class="smallbtn addPlayer">+ Add player</button>'; const names=pf.querySelector('.names'); for(let i=1;i<=2;i++)addName(names,`Player ${i}`);pf.querySelector('.addPlayer').onclick=()=>{if(names.children.length<8)addName(names,`Player ${names.children.length+1}`)}}root.querySelector('.source').onchange=e=>{root.querySelector('.artistField').classList.toggle('hidden',e.target.value!=='artist');root.querySelector('.listField').classList.toggle('hidden',!['playlist','custom'].includes(e.target.value))};target.append(f)}
function addName(box,value){const row=document.createElement('div');row.className='player-row';row.innerHTML=`<label>Player name<input maxlength="20" value="${value}"></label><button type="button" class="smallbtn">×</button>`;row.querySelector('button').onclick=()=>{if(box.children.length>2)row.remove()};box.append(row)}
function addArtist(box,value){const row=document.createElement('div');row.className='artist-row';row.innerHTML=`<input class="artist" maxlength="50" value="${esc(value)}" placeholder="Artist name"><button type="button" class="smallbtn" aria-label="Remove artist">×</button>`;row.querySelector('input').oninput=()=>{row.closest('.setup').dataset.poolReady='';row.closest('.setup').querySelector('.songPool').classList.add('hidden')};row.querySelector('button').onclick=()=>{if(box.children.length>1){row.remove();box.closest('.setup').dataset.poolReady=''}};box.append(row)}
setupForm($('#localForm'),true);setupForm($('#hostForm'),false);
function config(root){const selected=root._poolItems?$$('.song-check:checked',root).map(x=>root._poolItems[+x.dataset.index]):[];return{bidMode:root.querySelector('.bidMode').value,budget:+root.querySelector('.budget').value,rounds:+root.querySelector('.rounds').value,source:root.querySelector('.source').value,artists:$$('.artist',root).map(x=>x.value.trim()).filter(Boolean),raw:root.querySelector('.items').value.trim(),poolPrepared:root.dataset.poolReady==='yes',selectedItems:selected}}
async function fetchArtistSongs(artists){if(!artists.length)throw Error('Enter at least one artist.');const batches=await Promise.all(artists.map(async artist=>{const u=`https://itunes.apple.com/search?term=${encodeURIComponent(artist)}&entity=song&attribute=artistTerm&limit=50`;const d=await fetch(u).then(r=>{if(!r.ok)throw Error('Song search failed. Check your connection.');return r.json()}),needle=artist.toLowerCase();return d.results.filter(x=>x.trackName&&(x.artistName?.toLowerCase().includes(needle)||x.trackName.toLowerCase().includes(needle))).map(x=>({name:x.trackName,sub:x.artistName,art:x.artworkUrl100?.replace('100x100','300x300'),preview:x.previewUrl||''}))}));return[...new Map(batches.flat().map(x=>[`${x.name}|${x.sub}`.toLowerCase(),x])).values()]}
async function getItems(c,all=false){let items=[];if(c.source==='artist'){items=c.poolPrepared?c.selectedItems:await fetchArtistSongs(c.artists)}else if(c.source==='games')items=gameSeeds.map(name=>({name,sub:'Video game'}));else items=c.raw.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [name,...rest]=x.split(/\s+[—|-]\s+/);return{name,sub:rest.join(' — ')|| (c.source==='playlist'?'Song':'Custom item')}});items=[...new Map(items.map(x=>[`${x.name}|${x.sub}`.toLowerCase(),x])).values()];if(items.length<c.rounds)throw Error(`Select or add at least ${c.rounds} items.`);return all?items:shuffle(items).slice(0,c.rounds)}
async function previewSongPool(root){const button=root.querySelector('.poolButton'),pool=root.querySelector('.songPool');try{button.disabled=true;button.textContent='Loading songs…';const c=config(root),items=await fetchArtistSongs(c.artists);root._poolItems=items;root.dataset.poolReady='yes';pool.innerHTML=`<div class="pool-toolbar"><b>${items.length} songs found</b><button type="button" class="selectAll">Select all</button><button type="button" class="shufflePool">Shuffle</button></div><div class="song-grid">${items.map((x,i)=>`<label class="song-option"><input class="song-check" type="checkbox" data-index="${i}" checked><img src="${esc(x.art||'')}" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.sub)}</small>${x.preview?`<audio controls preload="none" src="${esc(x.preview)}"></audio>`:'<small>Preview unavailable</small>'}</span></label>`).join('')}</div>`;pool.classList.remove('hidden');pool.querySelector('.selectAll').onclick=e=>{const checks=$$('.song-check',pool),all=checks.every(x=>x.checked);checks.forEach(x=>x.checked=!all);e.currentTarget.textContent=all?'Select all':'Clear all'};pool.querySelector('.shufflePool').onclick=()=>{root._poolItems=shuffle(root._poolItems);previewSongPoolFromCache(root)};button.textContent='Refresh song pool'}catch(e){alert(e.message)}finally{button.disabled=false}}
function previewSongPoolFromCache(root){const pool=root.querySelector('.songPool');pool.querySelector('.song-grid').innerHTML=root._poolItems.map((x,i)=>`<label class="song-option"><input class="song-check" type="checkbox" data-index="${i}" checked><img src="${esc(x.art||'')}" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.sub)}</small>${x.preview?`<audio controls preload="none" src="${esc(x.preview)}"></audio>`:'<small>Preview unavailable</small>'}</span></label>`).join('')}
function gameConfig(c){const clean={...c};delete clean.selectedItems;delete clean.poolPrepared;return clean}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fresh(c,names,items){return{phase:'playing',config:c,items,round:0,players:names.map((name,i)=>({id:`p${i}-${Math.random().toString(36).slice(2,7)}`,name,budget:c.budget,picks:[],connected:true})),bids:{},auction:null,result:null,localStep:'handoff',localIndex:0,tieOffset:0}}
$('#startLocal').onclick=async()=>{const root=$('#localForm .setup'),names=$$('#localForm .names input').map(x=>x.value.trim()).filter(Boolean);try{const c=config(root);validate(c,names);state=fresh(gameConfig(c),names,await getItems(c));localNames=state.players.map(x=>x.id);role='local';beginRound();render()}catch(e){alert(e.message)}};
function validate(c,names){if(names.length<2||names.length>8)throw Error('Choose 2–8 players.');if(!Number.isInteger(c.budget)||c.budget<1)throw Error('Budget must be a positive whole number.');if(!Number.isInteger(c.rounds)||c.rounds<1||c.rounds>20)throw Error('Rounds must be 1–20.')}
function roomPath(code,suffix=''){return`rooms/${code.toUpperCase()}${suffix?'/'+suffix:''}`}
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
async function ensureAuth(){if(auth.currentUser)return auth.currentUser;authPromise??=signInAnonymously(auth).then(x=>x.user);return authPromise}
function clearOnlineListeners(){onlineUnsubs.forEach(x=>x());onlineUnsubs=[]}
function hydrateState(value){value.bids??={};value.players??=[];value.players.forEach(p=>p.picks??=[]);if(value.auction)value.auction.passed??=[];return value}
$('#createRoom').onclick=async()=>{
  const button=$('#createRoom'),name=$('#hostName').value.trim()||'Host',c=config($('#hostForm .setup'));
  try{button.disabled=true;button.textContent='Creating room…';validate(c,[name,'guest']);const [items,user]=await Promise.all([getItems(c),ensureAuth()]);let code;
    do{code=makeCode()}while((await get(ref(db,roomPath(code)))).exists());
    role='host';myId=user.uid;currentRoomCode=code;state=fresh(gameConfig(c),[name],items);state.players[0].id=myId;state.phase='lobby';history.replaceState({},'',urlFor('join',code));
    const roomRef=ref(db,roomPath(code));await set(roomRef,{hostUid:myId,createdAt:serverTimestamp(),state});await onDisconnect(roomRef).remove();attachHost(code);renderLobby();
  }catch(e){alert(firebaseMessage(e));button.disabled=false;button.textContent='Create room'}
};
function attachHost(code){clearOnlineListeners();
  onlineUnsubs.push(onChildAdded(ref(db,roomPath(code,'joinRequests')),async snap=>{const id=snap.key,request=snap.val();if(!state.players.some(p=>p.id===id)&&state.phase==='lobby'&&state.players.length<8){state.players.push({id,name:String(request.name||'Player').slice(0,20),budget:state.config.budget,picks:[],connected:true});await broadcast();renderLobby()}await remove(snap.ref)}));
  onlineUnsubs.push(onChildAdded(ref(db,roomPath(code,'actions')),async snap=>{const action=snap.val();if(state.phase==='playing')applyAction(snap.key,action.action,action.value);await remove(snap.ref)}));
  onlineUnsubs.push(onValue(ref(db,roomPath(code,'presence')),snap=>{if(!state)return;let changed=false;for(const p of state.players){if(p.id===myId)continue;const online=snap.child(p.id).exists();if(p.connected!==online){p.connected=online;changed=true;if(!online&&state.phase==='playing'&&state.config.bidMode==='open'&&state.auction&&!state.auction.passed.includes(p.id)){state.auction.passed.push(p.id);advanceAuction()}}}if(changed){broadcast();state.phase==='lobby'?renderLobby():render()}}));
}
$('#joinRoom').onclick=async()=>{
  const code=$('#joinCode').value.trim().toUpperCase(),name=$('#joinName').value.trim(),button=$('#joinRoom');
  if(code.length!==6||!name)return $('#joinError').textContent='Enter your name and six-character room code.';
  try{button.disabled=true;button.textContent='Joining…';$('#joinError').textContent='';const user=await ensureAuth(),roomRef=ref(db,roomPath(code)),snapshot=await get(roomRef);if(!snapshot.exists())throw Error('Room not found or host is offline.');const room=snapshot.val();if(Date.now()-(room.createdAt||0)>86400000)throw Error('This room has expired.');if(room.state?.phase!=='lobby')throw Error('This game has already started.');if((room.state?.players?.length||0)>=8)throw Error('Room is full.');
    role='guest';myId=user.uid;currentRoomCode=code;history.replaceState({},'',urlFor('join',code));await set(ref(db,roomPath(code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(code,`presence/${myId}`))).remove();await set(ref(db,roomPath(code,`joinRequests/${myId}`)),{name:name.slice(0,20),joinedAt:serverTimestamp()});
    clearOnlineListeners();onlineUnsubs.push(onValue(ref(db,roomPath(code,'state')),snap=>{if(!snap.exists()){show('join');$('#joinError').textContent='The host closed this room.';return}state=hydrateState(snap.val());if(!state.players.some(p=>p.id===myId))return;state.phase==='lobby'?renderLobby():render()}));
  }catch(e){$('#joinError').textContent=firebaseMessage(e);button.disabled=false;button.textContent='Join room'}
};
function firebaseMessage(e){if(e.message?.includes('Room')||e.message?.includes('room')||e.message?.includes('game'))return e.message;if(e.code==='auth/admin-restricted-operation')return'Anonymous sign-in is not enabled in Firebase Authentication.';if(e.code==='PERMISSION_DENIED'||e.code==='permission-denied')return'Firebase blocked the request. Publish the included database rules.';return'Could not connect to Firebase. '+(e.message||'Check your connection.')}
async function broadcast(){if(role==='host'&&currentRoomCode){const publicState=structuredClone(state);if(publicState.config.bidMode==='blind'&&!publicState.result)publicState.bids={};await set(ref(db,roomPath(currentRoomCode,'state')),publicState)}}
function renderLobby(){show('lobby');$('#roomCode').textContent=currentRoomCode||'…';$('#inviteLink').value=inviteUrl(currentRoomCode);$('#connectionStatus').textContent=role==='host'?'Share the link or room code. Keep this tab open.':'Connected through Firebase — waiting for the host.';$('#lobbySettings').innerHTML=`<p><b>${state.config.bidMode==='open'?'Open Auction':'Blind Bid'}</b> · $${state.config.budget} budget · ${state.config.rounds} rounds</p>`;$('#lobbyPlayers').innerHTML=state.players.map(p=>`<span class="pill">${esc(p.name)}</span>`).join('');$('#startOnline').classList.toggle('hidden',role!=='host');$('#startOnline').disabled=state.players.length<2;$('#lobbyHint').textContent=state.players.length<2?'Waiting for at least one more player…':''}
$('#startOnline').onclick=()=>{if(role==='host'&&state.players.length>=2){state.phase='playing';beginRound();broadcast();render()}};
function beginRound(){state.bids={};state.result=null;state.localIndex=0;state.localStep='handoff';if(state.config.bidMode==='open'){const eligible=state.players.filter(p=>p.connected!==false&&p.budget>0);state.auction={highBid:0,highBidder:null,passed:state.players.filter(p=>!eligible.includes(p)).map(p=>p.id),turn:eligible[0]?.id||null}}}
function current(){return state.items[state.round]} function player(id){return state.players.find(p=>p.id===id)}
function applyAction(id,action,value){if(state.result)return;const p=player(id);if(!p||p.connected===false)return;if(state.config.bidMode==='blind'){if(action!=='bid'||state.bids[id]!=null)return;const n=Number(value);if(!Number.isInteger(n)||n<0||n>p.budget)return;state.bids[id]=n;if(activePlayers().every(x=>state.bids[x.id]!=null))finishBlind()}else{const a=state.auction;if(a.turn!==id||a.passed.includes(id))return;if(action==='pass'){a.passed.push(id);advanceAuction()}else if(action==='bid'){const n=Number(value);if(!Number.isInteger(n)||n<=a.highBid||n>p.budget)return;a.highBid=n;a.highBidder=id;advanceAuction()}}broadcast();render()}
function activePlayers(){return state.players.filter(p=>p.connected!==false)}
function finishBlind(){const entries=activePlayers().map(p=>({p,b:state.bids[p.id]}));const max=Math.max(...entries.map(x=>x.b));const tied=entries.filter(x=>x.b===max);const ordered=[...state.players.slice(state.tieOffset),...state.players.slice(0,state.tieOffset)];const winner=ordered.find(p=>tied.some(x=>x.p.id===p.id));state.tieOffset=(state.players.indexOf(winner)+1)%state.players.length;award(winner,max,entries)}
function advanceAuction(){const a=state.auction,eligible=activePlayers().filter(p=>!a.passed.includes(p.id)&&p.budget>a.highBid);if(a.highBidder&&!a.passed.includes(a.highBidder)&&eligible.filter(p=>p.id!==a.highBidder).length===0)return award(player(a.highBidder),a.highBid,[]);if(!eligible.length){if(a.highBidder)return award(player(a.highBidder),a.highBid,[]);return award(null,0,[])}const start=state.players.findIndex(p=>p.id===a.turn);for(let n=1;n<=state.players.length;n++){const p=state.players[(start+n)%state.players.length];if(eligible.some(x=>x.id===p.id)&&p.id!==a.highBidder){a.turn=p.id;return}}if(a.highBidder)award(player(a.highBidder),a.highBid,[])}
function award(winner,amount,entries){if(winner){winner.budget-=amount;winner.picks.push({...current(),price:amount})}state.result={winner:winner?.id||null,amount,entries}}
function send(action,value){if(role==='guest')set(ref(db,roomPath(currentRoomCode,`actions/${myId}`)),{action,value:value??null,nonce:crypto.randomUUID()}).catch(e=>alert(firebaseMessage(e)));else applyAction(myId,action,value)}
function render(){if(!state)return; if(state.phase==='finished')return renderFinal();show('game');const item=current(),audio=$('#itemPreview');$('#roundLabel').textContent=`Round ${state.round+1} of ${state.config.rounds}`;$('#itemName').textContent=item.name;$('#itemSubtitle').textContent=item.sub||'';$('#itemArt').classList.toggle('hidden',!item.art);if(item.art)$('#itemArt').src=item.art;audio.classList.toggle('hidden',!item.preview);if(item.preview&&audio.src!==item.preview){audio.src=item.preview;audio.load()}if(!item.preview){audio.pause();audio.removeAttribute('src')}$('#scoreboard').innerHTML=state.players.map(p=>`<div class="score"><b>${esc(p.name)}</b><span>$${p.budget} left · ${p.picks.length} picks</span></div>`).join('');$('#actionCard').classList.toggle('hidden',Boolean(state.result));$('#resultsCard').classList.toggle('hidden',!state.result);if(state.result)return renderResult();state.config.bidMode==='blind'?renderBlind():renderAuction()}
function renderBlind(){const card=$('#actionCard');if(role==='local'){const p=state.players[state.localIndex];if(state.localStep==='handoff'){card.innerHTML=`<h3>Pass to ${esc(p.name)}</h3><p>Tap when only ${esc(p.name)} can see the screen.</p><button class="primary" id="ready">I’m ready</button>`;$('#ready').onclick=()=>{state.localStep='bid';render()}}else{card.innerHTML=bidForm(p,0,'Lock secret bid');bindBid(p.id,true)}}else{const p=player(myId),done=state.bids[myId]!=null;card.innerHTML=done?'<h3>Bid locked</h3><p>Waiting for the other players…</p>':bidForm(p,0,'Lock secret bid');if(!done)bindBid(p.id,false)}}
function bidForm(p,min,label){return`<h3>${esc(p.name)}’s bid</h3><p>Available: $${p.budget}</p><div class="bidbox"><div><label>Choose your bid</label><div class="bid-stepper"><button id="bidMinus" type="button" aria-label="Decrease bid">−</button><output id="bidDisplay">$${min}</output><button id="bidPlus" type="button" aria-label="Increase bid">+</button><input id="bidValue" type="hidden" value="${min}"></div></div><button id="bidBtn">${label}</button></div><p id="bidError" class="error"></p>`}
function bindStepper(min,max){const input=$('#bidValue'),display=$('#bidDisplay'),minus=$('#bidMinus'),plus=$('#bidPlus');const update=n=>{n=Math.max(min,Math.min(max,n));input.value=n;display.textContent=`$${n}`;minus.disabled=n<=min;plus.disabled=n>=max};minus.onclick=()=>update(Number(input.value)-1);plus.onclick=()=>update(Number(input.value)+1);update(min)}
function bindBid(id,local){const p=player(id);bindStepper(0,p.budget);$('#bidBtn').onclick=()=>{const n=Number($('#bidValue').value);if(!Number.isInteger(n)||n<0||n>p.budget)return $('#bidError').textContent=`Enter a whole dollar amount from $0 to $${p.budget}.`;if(local){state.bids[id]=n;state.localIndex++;if(state.localIndex>=state.players.length)finishBlind();else state.localStep='handoff';render()}else send('bid',n)}}
function renderAuction(){const a=state.auction,turn=player(a.turn),high=a.highBidder?player(a.highBidder):null;$('#scoreboard').innerHTML=state.players.map(p=>`<div class="score ${p.id===a.turn?'turn':''}"><b>${esc(p.name)}</b><span>$${p.budget} left ${a.passed.includes(p.id)?'· Passed':''}</span></div>`).join('');const card=$('#actionCard');card.innerHTML=`<div class="auction"><p>Current bid</p><strong>$${a.highBid}</strong><p>${high?`by ${esc(high.name)}`:'No bids yet'}</p></div><div id="turnAction"></div>`;const act=$('#turnAction');if(role==='local'){const p=turn;act.innerHTML=`<h3>Pass to ${esc(p.name)}</h3><p>All auction activity is visible.</p><button id="localReady" class="primary">Take my turn</button>`;$('#localReady').onclick=()=>renderAuctionControls(p)}else if(myId===a.turn)renderAuctionControls(player(myId));else act.innerHTML=`<p class="muted">Waiting for ${esc(turn?.name||'the next player')}…</p>`}
function renderAuctionControls(p){const act=$('#turnAction'),min=state.auction.highBid+1;act.innerHTML=`<h3>${esc(p.name)}, your turn</h3>${bidForm(p,min,'Place bid')}<button id="passBtn">Pass for this item</button>`;bindStepper(min,p.budget);$('#bidBtn').onclick=()=>{const n=Number($('#bidValue').value);if(!Number.isInteger(n)||n<min||n>p.budget)return $('#bidError').textContent=`Bid a whole dollar amount from $${min} to $${p.budget}.`;if(role==='local')applyAction(p.id,'bid',n);else send('bid',n)};$('#passBtn').onclick=()=>role==='local'?applyAction(p.id,'pass'):send('pass')}
function renderResult(){const r=state.result,w=r.winner?player(r.winner):null,card=$('#resultsCard');$('#actionCard').classList.add('hidden');card.innerHTML=`<h3>${w?`<span class="winner">${esc(w.name)}</span> wins ${esc(current().name)} for $${r.amount}`:`No one drafted ${esc(current().name)}`}</h3>${r.entries?.length?'<div>'+r.entries.sort((a,b)=>b.b-a.b).map(x=>`<div class="result-row">${esc(x.p.name)} <b>$${x.b}</b></div>`).join('')+'</div>':''}${(role==='host'||role==='local')?'<button id="nextRound" class="primary">'+(state.round+1>=state.config.rounds?'See final lineups':'Next round')+'</button>':'<p class="muted">Waiting for the host…</p>'}`;const b=$('#nextRound');if(b)b.onclick=()=>{state.round++;$('#actionCard').classList.remove('hidden');if(state.round>=state.config.rounds)state.phase='finished';else beginRound();broadcast();render()}}
function renderFinal(){show('final');$('#finalResults').innerHTML=state.players.map(p=>`<div class="final-player"><h3>${esc(p.name)} · $${p.budget} left</h3>${p.picks.length?p.picks.map(x=>`<p>${esc(x.name)} — $${x.price}</p>`).join(''):'<p class="muted">No picks</p>'}</div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
