import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged, GoogleAuthProvider, linkWithPopup, signInWithPopup, signInWithCredential, EmailAuthProvider, linkWithCredential, signInWithEmailAndPassword, updateProfile, sendPasswordResetEmail, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase, ref, get, set, update, remove, runTransaction, onValue, onChildAdded, onDisconnect, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import { SPOTIFY_CLIENT_ID, SPOTIFY_REDIRECT_URI } from "./spotify-config.js";

"use strict";
const firebaseConfig={apiKey:"AIzaSyBWRTufmXZpw5oMjw6Q7LGuBfm-F_TORgY",authDomain:"draft-duel-832d7.firebaseapp.com",databaseURL:"https://draft-duel-832d7-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"draft-duel-832d7",storageBucket:"draft-duel-832d7.firebasestorage.app",messagingSenderId:"980217895202",appId:"1:980217895202:web:866eb7a7b64ec515512d7b",measurementId:"G-3ZX24EZ405"};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getDatabase(firebaseApp);
// Firebase restores a saved account asynchronously. Wait for that first result
// before creating a temporary guest account, otherwise a refresh can replace a
// real signed-in session with a new anonymous one.
const initialAuthReady=new Promise(resolve=>{let stop=()=>{};stop=onAuthStateChanged(auth,user=>{stop();resolve(user)})});
const $=s=>document.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const screens=$$('.screen'); let role='local',myId=null,currentRoomCode='',onlineHostUid=null,hostMigrationTimer=null,authPromise=null,onlineUnsubs=[],liveDirectoryUnsub=null,spectatorUnsub=null,pendingBidRound=-1,currentAccountData=null,pendingChallengeTarget=null,resumeAttempted=false,deferredInstallPrompt=null;
const recordedGames=new Set(),avatarOptions=['🎵','🎧','🎤','🎸','💿','🔥','⚡','👑'];
let state=null, localNames=[]; const gameSeeds=['The Legend of Zelda: Breath of the Wild','Minecraft','Mario Kart 8 Deluxe','God of War','Fortnite','Grand Theft Auto V','Elden Ring','Red Dead Redemption 2','Super Mario Odyssey','The Last of Us','Rocket League','Hades'];
function show(id){screens.forEach(x=>x.classList.toggle('hidden',x.id!==id));scrollTo(0,0)}
const pageToScreen={home:'home',local:'localSetup',host:'hostSetup',join:'join',spectate:'spectate',account:'account',community:'community'};
function urlFor(page,room=''){const u=new URL(location.href);u.search='';u.hash='';if(page!=='home')u.searchParams.set('page',page);if(room)u.searchParams.set('room',room);return u}
function navigate(page,replace=false){const screen=pageToScreen[page]||'home',u=urlFor(page);history[replace?'replaceState':'pushState']({},'',u);show(screen);if(page==='spectate')loadLiveGames();if(page==='community')loadCommunity();if(page==='join'){const code=new URL(location.href).searchParams.get('room');if(code)$('#joinCode').value=code.toUpperCase()}}
function routeFromUrl(){const u=new URL(location.href),room=u.searchParams.get('room')||'',page=u.searchParams.get('page')||'home';if(page==='join'&&room)$('#joinCode').value=room.toUpperCase();if(page==='spectate'&&room)return watchGame(room,false);show(pageToScreen[page]||'home');if(page==='spectate')loadLiveGames();if(page==='community')loadCommunity()}
$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(({localSetup:'local',hostSetup:'host'}[b.dataset.nav]||b.dataset.nav)));
addEventListener('popstate',routeFromUrl);routeFromUrl();
$('#howButton').onclick=()=>$('#howDialog').showModal();$('#closeHow').onclick=()=>$('#howDialog').close();
function inviteUrl(code){return urlFor('join',code).href}
$('#copyInvite').onclick=async()=>{const link=inviteUrl(currentRoomCode);try{await navigator.clipboard.writeText(link)}catch{const input=$('#inviteLink');input.focus();input.select();document.execCommand('copy')}$('#copyStatus').textContent='Invite link copied!';setTimeout(()=>$('#copyStatus').textContent='',2500)};
function setupForm(target,local){const f=$('#setupTemplate').content.cloneNode(true),root=f.querySelector('.setup'),pf=root.querySelector('.playerFields'),artists=root.querySelector('.artists');addArtist(artists,'Bruno Mars');root.querySelector('.addArtist').onclick=()=>{if(artists.children.length<8)addArtist(artists,'')};root.querySelector('.poolButton').onclick=()=>previewSongPool(root);if(local){pf.innerHTML='<h3>Players</h3><div class="names"></div><button type="button" class="smallbtn addPlayer">+ Add player</button>'; const names=pf.querySelector('.names'); for(let i=1;i<=2;i++)addName(names,`Player ${i}`);pf.querySelector('.addPlayer').onclick=()=>{if(names.children.length<8)addName(names,`Player ${names.children.length+1}`)}}root.querySelector('.source').onchange=e=>{root.querySelector('.artistField').classList.toggle('hidden',e.target.value!=='artist');root.querySelector('.listField').classList.toggle('hidden',!['playlist','custom'].includes(e.target.value))};target.append(f)}
function addName(box,value){const row=document.createElement('div');row.className='player-row';row.innerHTML=`<label>Player name<input maxlength="20" value="${value}"></label><button type="button" class="smallbtn">×</button>`;row.querySelector('button').onclick=()=>{if(box.children.length>2)row.remove()};box.append(row)}
function addArtist(box,value){const row=document.createElement('div');row.className='artist-row';row.innerHTML=`<input class="artist" maxlength="50" value="${esc(value)}" placeholder="Artist name"><button type="button" class="smallbtn" aria-label="Remove artist">×</button>`;row.querySelector('input').oninput=()=>{row.closest('.setup').dataset.poolReady='';row.closest('.setup').querySelector('.songPool').classList.add('hidden')};row.querySelector('button').onclick=()=>{if(box.children.length>1){row.remove();box.closest('.setup').dataset.poolReady=''}};box.append(row)}
setupForm($('#localForm'),true);setupForm($('#hostForm'),false);
function config(root){const selected=root._poolItems?$$('.song-check:checked',root).map(x=>root._poolItems[+x.dataset.index]):[];return{bidMode:root.querySelector('.bidMode').value,budget:+root.querySelector('.budget').value,rounds:+root.querySelector('.rounds').value,source:root.querySelector('.source').value,artists:$$('.artist',root).map(x=>x.value.trim()).filter(Boolean),raw:root.querySelector('.items').value.trim(),poolPrepared:root.dataset.poolReady==='yes',selectedItems:selected}}
async function fetchArtistSongs(artists){if(!artists.length)throw Error('Enter at least one artist.');const batches=await Promise.all(artists.map(async artist=>{const u=`https://itunes.apple.com/search?term=${encodeURIComponent(artist)}&entity=song&attribute=artistTerm&limit=50`;const d=await fetch(u).then(r=>{if(!r.ok)throw Error('Song search failed. Check your connection.');return r.json()}),needle=artist.toLowerCase();return d.results.filter(x=>x.trackName&&(x.artistName?.toLowerCase().includes(needle)||x.trackName.toLowerCase().includes(needle))).map(x=>({name:x.trackName,sub:x.artistName,art:x.artworkUrl100?.replace('100x100','300x300'),preview:x.previewUrl||''}))}));return[...new Map(batches.flat().map(x=>[`${x.name}|${x.sub}`.toLowerCase(),x])).values()]}
async function getItems(c,all=false){let items=[];if(c.source==='artist'){items=c.poolPrepared?c.selectedItems:await fetchArtistSongs(c.artists)}else if(c.source==='games')items=gameSeeds.map(name=>({name,sub:'Video game'}));else items=c.raw.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const [name,...rest]=x.split(/\s+[—|-]\s+/);return{name,sub:rest.join(' — ')|| (c.source==='playlist'?'Song':'Custom item')}});items=[...new Map(items.map(x=>[`${x.name}|${x.sub}`.toLowerCase(),x])).values()];if(items.length<c.rounds)throw Error(`Select or add at least ${c.rounds} items.`);return all?items:shuffle(items).slice(0,c.rounds)}
async function previewSongPool(root){const button=root.querySelector('.poolButton'),pool=root.querySelector('.songPool');try{button.disabled=true;button.textContent='Loading songs…';const c=config(root),items=await fetchArtistSongs(c.artists);root._poolItems=items;root.dataset.poolReady='yes';pool.innerHTML=`<div class="pool-toolbar"><b>${items.length} songs found</b><button type="button" class="selectAll">Select all</button><button type="button" class="shufflePool">Shuffle</button></div><div class="song-grid">${items.map((x,i)=>`<label class="song-option"><input class="song-check" type="checkbox" data-index="${i}" checked><img src="${esc(x.art||'')}" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.sub)}</small>${x.preview?`<audio controls preload="none" src="${esc(x.preview)}"></audio>`:'<small>Preview unavailable</small>'}</span></label>`).join('')}</div>`;pool.classList.remove('hidden');pool.querySelector('.selectAll').onclick=e=>{const checks=$$('.song-check',pool),all=checks.every(x=>x.checked);checks.forEach(x=>x.checked=!all);e.currentTarget.textContent=all?'Select all':'Clear all'};pool.querySelector('.shufflePool').onclick=()=>{root._poolItems=shuffle(root._poolItems);previewSongPoolFromCache(root)};button.textContent='Refresh song pool'}catch(e){alert(e.message)}finally{button.disabled=false}}
function previewSongPoolFromCache(root){const pool=root.querySelector('.songPool');pool.querySelector('.song-grid').innerHTML=root._poolItems.map((x,i)=>`<label class="song-option"><input class="song-check" type="checkbox" data-index="${i}" checked><img src="${esc(x.art||'')}" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.sub)}</small>${x.preview?`<audio controls preload="none" src="${esc(x.preview)}"></audio>`:'<small>Preview unavailable</small>'}</span></label>`).join('')}
function gameConfig(c){const clean={...c};delete clean.selectedItems;delete clean.poolPrepared;return clean}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fresh(c,names,items){return{gameId:`g-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,phase:'playing',config:c,items,round:0,players:names.map((name,i)=>({id:`p${i}-${Math.random().toString(36).slice(2,7)}`,name,budget:c.budget,picks:[],connected:true})),bids:{},auction:null,result:null,matchWinner:null,localStep:'handoff',localIndex:0,tieOffset:0}}
$('#startLocal').onclick=async()=>{const root=$('#localForm .setup'),names=$$('#localForm .names input').map(x=>x.value.trim()).filter(Boolean);try{const c=config(root);validate(c,names);state=fresh(gameConfig(c),names,await getItems(c));localNames=state.players.map(x=>x.id);role='local';beginRound();render()}catch(e){alert(e.message)}};
function validate(c,names){if(names.length<2||names.length>8)throw Error('Choose 2–8 players.');if(!Number.isInteger(c.budget)||c.budget<1)throw Error('Budget must be a positive whole number.');if(!Number.isInteger(c.rounds)||c.rounds<1||c.rounds>20)throw Error('Rounds must be 1–20.')}
function roomPath(code,suffix=''){return`rooms/${code.toUpperCase()}${suffix?'/'+suffix:''}`}
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
async function ensureAuth(){await initialAuthReady;if(auth.currentUser)return auth.currentUser;authPromise??=signInAnonymously(auth).then(x=>x.user).finally(()=>{authPromise=null});return authPromise}
const googleProvider=new GoogleAuthProvider();googleProvider.setCustomParameters({prompt:'select_account'});
function accountName(user){return user.displayName||user.email?.split('@')[0]||'Draft player'}
function renderAccount(user){const member=user&&!user.isAnonymous,name=member?(currentAccountData?.account?.username||accountName(user)):'' ,avatar=currentAccountData?.account?.avatar||(member?name.charAt(0).toUpperCase():'?');$('#accountGuest').classList.toggle('hidden',member);$('#accountMember').classList.toggle('hidden',!member);$('#accountLabel').textContent=member?name:'Account';$('#accountAvatar').textContent=avatar;if(member){$('#memberName').textContent=name;$('#memberEmail').textContent=user.email||'Connected account';$('#memberAvatar').textContent=avatar}}
async function saveAccountProfile(user){if(!user||user.isAnonymous)return;await update(ref(db,`users/${user.uid}/account`),{displayName:accountName(user),email:user.email||'',provider:user.providerData[0]?.providerId||'password',updatedAt:serverTimestamp()}).catch(()=>{})}
async function loadAccountDashboard(user){if(!user||user.isAnonymous){currentAccountData=null;renderAccount(user);return}const snap=await get(ref(db,`users/${user.uid}`)).catch(()=>null);currentAccountData=snap?.val()||{};renderAccount(user);const username=currentAccountData.account?.username||accountName(user),avatar=currentAccountData.account?.avatar||avatarOptions[0];$('#profileUsername').value=username;if($('#hostName').value==='Host')$('#hostName').value=username;if(!$('#joinName').value)$('#joinName').value=username;renderAvatarChoices(avatar);renderCareer(currentAccountData.stats||{});renderHistory(currentAccountData.history||{});renderSpotify(currentAccountData.musicProfile||null);renderTaste();renderAchievements(currentAccountData.stats||{});set(ref(db,`publicProfiles/${user.uid}`),{username,avatar,stats:currentAccountData.stats||{},updatedAt:serverTimestamp()}).catch(()=>{})}
onAuthStateChanged(auth,async user=>{renderAccount(user);if(user&&!user.isAnonymous){await saveAccountProfile(user);await loadAccountDashboard(user)}if(user&&!resumeAttempted){resumeAttempted=true;resumeOnlineSession().catch(()=>{})}});
function renderAvatarChoices(selected){$('#avatarChoices').innerHTML=avatarOptions.map(x=>`<label><input type="radio" name="avatar" value="${x}" ${x===selected?'checked':''}><span>${x}</span></label>`).join('')}
function renderCareer(stats){$('#careerStats').innerHTML=`<div><b>${stats.games||0}</b><span>Games</span></div><div><b>${stats.wins||0}</b><span>Wins</span></div><div><b>${stats.losses||0}</b><span>Losses</span></div><div><b>${stats.itemsWon||0}</b><span>Items drafted</span></div>`}
function renderHistory(history){const games=Object.values(history).sort((a,b)=>(b.completedAt||0)-(a.completedAt||0)).slice(0,10);$('#gameHistory').innerHTML=games.length?games.map(g=>`<article class="history-row"><span class="${g.won?'history-win':'history-loss'}">${g.won?'WIN':'LOSS'}</span><div><b>${esc(g.mode||'Draft Duel')}</b><small>${esc((g.players||[]).join(' vs '))}</small></div><time>${new Date(g.completedAt).toLocaleDateString()}</time></article>`).join(''):'<p class="muted">No completed games yet.</p>'}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const user=auth.currentUser;if(!user||user.isAnonymous)return;const username=$('#profileUsername').value.trim(),avatar=$('input[name="avatar"]:checked')?.value||avatarOptions[0];if(username.length<2)return $('#profileNotice').textContent='Username must be at least two characters.';try{await updateProfile(user,{displayName:username});await update(ref(db,`users/${user.uid}/account`),{username,avatar,updatedAt:serverTimestamp()});await set(ref(db,`publicProfiles/${user.uid}`),{username,avatar,stats:currentAccountData?.stats||{},updatedAt:serverTimestamp()});$('#profileNotice').className='success';$('#profileNotice').textContent='Profile saved.';await loadAccountDashboard(user)}catch(err){$('#profileNotice').className='error';$('#profileNotice').textContent=firebaseMessage(err)}};
function spotifyTokenKey(){return`draftDuelSpotify:${auth.currentUser?.uid||'guest'}`}
function randomString(length=64){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',bytes=crypto.getRandomValues(new Uint8Array(length));return[...bytes].map(x=>chars[x%chars.length]).join('')}
async function pkceChallenge(verifier){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
$('#connectSpotify').onclick=async()=>{const user=auth.currentUser;if(!user||user.isAnonymous)return setSpotifyNotice('Create or sign into a Draft Duel account first.');if(!SPOTIFY_CLIENT_ID)return setSpotifyNotice('Add your Spotify Client ID to spotify-config.js first.');if(currentAccountData?.musicProfile&&localStorage.getItem(spotifyTokenKey()))return importSpotifyTaste().then(()=>setSpotifyNotice('Spotify taste refreshed.',true)).catch(x=>setSpotifyNotice(x.message));const verifier=randomString(),stateValue=randomString(32),challenge=await pkceChallenge(verifier);sessionStorage.setItem('spotify_verifier',verifier);sessionStorage.setItem('spotify_state',stateValue);sessionStorage.setItem('spotify_uid',user.uid);const u=new URL('https://accounts.spotify.com/authorize');u.search=new URLSearchParams({client_id:SPOTIFY_CLIENT_ID,response_type:'code',redirect_uri:SPOTIFY_REDIRECT_URI,scope:'user-read-private user-top-read',code_challenge_method:'S256',code_challenge:challenge,state:stateValue}).toString();location.href=u.href};
function setSpotifyNotice(message,success=false){$('#spotifyNotice').className=success?'success':'error';$('#spotifyNotice').textContent=message}
async function readSpotifyResponse(response,fallback){const text=await response.text();let body=null;if(text){try{body=JSON.parse(text)}catch{const message=text.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();if(!response.ok)throw Error(message.slice(0,240)||fallback);throw Error(`${fallback} Spotify returned an unexpected response.`)}}if(!response.ok){const message=body?.error_description||body?.error?.message||(typeof body?.error==='string'?body.error:'')||body?.message||fallback;throw Error(message)}return body||{}}
async function handleSpotifyCallback(){const u=new URL(location.href),code=u.searchParams.get('code'),returnedState=u.searchParams.get('state');if(!code)return;if(!SPOTIFY_CLIENT_ID)return;history.replaceState({},'',urlFor('account'));show('account');try{const expected=sessionStorage.getItem('spotify_state'),verifier=sessionStorage.getItem('spotify_verifier'),uid=sessionStorage.getItem('spotify_uid');if(!expected||returnedState!==expected||!verifier)throw Error('Spotify sign-in could not be verified. Please try again.');await initialAuthReady;const user=auth.currentUser;if(!user)throw Error('Sign back into Draft Duel and reconnect Spotify.');if(user.uid!==uid)throw Error('Sign back into the same Draft Duel account and reconnect Spotify.');const response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:SPOTIFY_CLIENT_ID,grant_type:'authorization_code',code,redirect_uri:SPOTIFY_REDIRECT_URI,code_verifier:verifier})});const token=await readSpotifyResponse(response,'Spotify token exchange failed.');saveSpotifyToken(token);sessionStorage.removeItem('spotify_state');sessionStorage.removeItem('spotify_verifier');sessionStorage.removeItem('spotify_uid');await importSpotifyTaste();setSpotifyNotice('Spotify connected and music taste imported.',true)}catch(e){setSpotifyNotice(e.message)}}
function saveSpotifyToken(token){const previous=JSON.parse(localStorage.getItem(spotifyTokenKey())||'{}');localStorage.setItem(spotifyTokenKey(),JSON.stringify({...previous,...token,expires_at:Date.now()+(token.expires_in||3600)*1000-60000}))}
async function spotifyAccessToken(){let token=JSON.parse(localStorage.getItem(spotifyTokenKey())||'null');if(!token)throw Error('Connect Spotify first.');if(Date.now()<token.expires_at)return token.access_token;if(!token.refresh_token)throw Error('Reconnect Spotify to refresh access.');const response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:SPOTIFY_CLIENT_ID,grant_type:'refresh_token',refresh_token:token.refresh_token})}),next=await readSpotifyResponse(response,'Spotify refresh failed.');saveSpotifyToken(next);return next.access_token}
async function spotifyGet(path){const token=await spotifyAccessToken(),response=await fetch(`https://api.spotify.com/v1${path}`,{headers:{Authorization:`Bearer ${token}`}}),body=await readSpotifyResponse(response,'Spotify request failed.');return body}
async function importSpotifyTaste(){const user=auth.currentUser;if(!user||user.isAnonymous)throw Error('Sign into Draft Duel first.');setSpotifyNotice('Importing your top music…');const [profile,artists,tracks]=await Promise.all([spotifyGet('/me'),spotifyGet('/me/top/artists?time_range=medium_term&limit=20'),spotifyGet('/me/top/tracks?time_range=medium_term&limit=20')]);const musicProfile={spotifyId:profile.id,displayName:profile.display_name||'',updatedAt:Date.now(),topArtists:artists.items.map(x=>({id:x.id,name:x.name,image:x.images?.[1]?.url||x.images?.[0]?.url||'',genres:(x.genres||[]).slice(0,3)})),topTracks:tracks.items.map(x=>({id:x.id,name:x.name,artists:x.artists.map(a=>a.name),image:x.album?.images?.[1]?.url||x.album?.images?.[0]?.url||''}))};await set(ref(db,`users/${user.uid}/musicProfile`),musicProfile);currentAccountData??={};currentAccountData.musicProfile=musicProfile;renderSpotify(musicProfile);return musicProfile}
function renderSpotify(profile){const connected=Boolean(profile);$('#spotifyProfile').classList.toggle('hidden',!connected);$('#connectSpotify').textContent=connected?(localStorage.getItem(spotifyTokenKey())?'Refresh Spotify taste':'Reconnect Spotify'):'Connect Spotify';if(!SPOTIFY_CLIENT_ID){$('#connectSpotify').textContent='Spotify setup required';$('#spotifyNotice').className='muted';$('#spotifyNotice').textContent='Add the Spotify Client ID to spotify-config.js to enable connection.'}if(!connected)return;$('#topArtists').innerHTML=`<h4>Top artists</h4><div class="taste-grid">${(profile.topArtists||[]).slice(0,10).map(x=>`<article><img src="${esc(x.image)}" alt=""><b>${esc(x.name)}</b></article>`).join('')}</div>`;$('#topTracks').innerHTML=`<h4>Top tracks</h4><ol class="track-list">${(profile.topTracks||[]).slice(0,10).map(x=>`<li><img src="${esc(x.image)}" alt=""><span><b>${esc(x.name)}</b><small>${esc((x.artists||[]).join(', '))}</small></span></li>`).join('')}</ol>`}
handleSpotifyCallback();
function setAccountNotice(message,success=false){$('#accountError').className=success?'success':'error';$('#accountError').textContent=message}
function accountChangeBlocked(){if(['host','guest'].includes(role)&&state&&['lobby','playing'].includes(state.phase)){setAccountNotice('Finish or leave the current online game before changing accounts.');return true}return false}
$$('[data-account-tab]').forEach(b=>b.onclick=()=>{$$('[data-account-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#signupForm').classList.toggle('hidden',b.dataset.accountTab!=='signup');$('#signinForm').classList.toggle('hidden',b.dataset.accountTab!=='signin');setAccountNotice('')});
$('#googleAccount').onclick=async()=>{if(accountChangeBlocked())return;const button=$('#googleAccount');try{button.disabled=true;setAccountNotice('');let result;const current=await ensureAuth();if(current.isAnonymous){try{result=await linkWithPopup(current,googleProvider)}catch(e){const credential=GoogleAuthProvider.credentialFromError(e);if(!credential||!['auth/credential-already-in-use','auth/email-already-in-use'].includes(e.code))throw e;await signOut(auth);authPromise=null;result=await signInWithCredential(auth,credential)}}else result=await signInWithPopup(auth,googleProvider);await saveAccountProfile(result.user);show('account')}catch(e){setAccountNotice(accountMessage(e))}finally{button.disabled=false}};
$('#signupForm').onsubmit=async e=>{e.preventDefault();if(accountChangeBlocked())return;const button=e.currentTarget.querySelector('button[type="submit"]');try{button.disabled=true;setAccountNotice('');const current=await ensureAuth(),credential=EmailAuthProvider.credential($('#signupEmail').value.trim(),$('#signupPassword').value);let result;if(current.isAnonymous)result=await linkWithCredential(current,credential);else throw Error('You are already signed in.');await updateProfile(result.user,{displayName:$('#signupName').value.trim()});await saveAccountProfile(result.user);renderAccount(result.user)}catch(err){setAccountNotice(accountMessage(err))}finally{button.disabled=false}};
$('#signinForm').onsubmit=async e=>{e.preventDefault();if(accountChangeBlocked())return;const button=e.currentTarget.querySelector('button[type="submit"]'),email=$('#signinEmail').value.trim(),password=$('#signinPassword').value;try{button.disabled=true;setAccountNotice('');if(auth.currentUser?.isAnonymous){await signOut(auth);authPromise=null}const result=await signInWithEmailAndPassword(auth,email,password);await saveAccountProfile(result.user)}catch(err){setAccountNotice(accountMessage(err));await ensureAuth().catch(()=>{})}finally{button.disabled=false}};
$('#resetPassword').onclick=async()=>{const email=$('#signinEmail').value.trim();if(!email)return setAccountNotice('Enter your email address first.');try{await sendPasswordResetEmail(auth,email);setAccountNotice('Password reset email sent.',true)}catch(e){setAccountNotice(accountMessage(e))}};
$('#signOutAccount').onclick=async()=>{if(accountChangeBlocked())return;await signOut(auth);authPromise=null;await ensureAuth();navigate('home')};
function accountMessage(e){const messages={'auth/email-already-in-use':'That email already has an account. Choose Sign in instead.','auth/invalid-credential':'Incorrect email or password.','auth/weak-password':'Use a password with at least six characters.','auth/popup-closed-by-user':'The sign-in window was closed.','auth/popup-blocked':'Your browser blocked the sign-in window. Allow pop-ups and try again.','auth/unauthorized-domain':'Add this GitHub Pages domain under Firebase Authentication → Settings → Authorized domains.','auth/operation-not-allowed':'Enable this sign-in method in Firebase Authentication.'};return messages[e.code]||e.message||'Account request failed.'}
function clearOnlineListeners(){onlineUnsubs.forEach(x=>x());onlineUnsubs=[]}
function hydrateState(value){value.bids??={};value.bidStatus??=[];value.players??=[];value.players.forEach(p=>p.picks??=[]);if(value.auction)value.auction.passed??=[];return value}
function publicGameState(source){const copy=structuredClone(source);copy.bidStatus=Object.keys(source.bids||{});copy.bids={};return copy}
async function watchActiveCount(){try{await ensureAuth();onValue(ref(db,'publicGames'),snap=>{const games=Object.values(snap.val()||{}).filter(g=>g.state?.phase!=='finished'&&Date.now()-(g.updatedAt||0)<86400000);$('#activeCount').textContent=games.length},()=>{$('#activeCount').textContent='—'})}catch{$('#activeCount').textContent='—'}}
watchActiveCount();
$('#createRoom').onclick=async()=>{
  const button=$('#createRoom'),name=$('#hostName').value.trim()||'Host',c=config($('#hostForm .setup'));
  try{button.disabled=true;button.textContent='Creating room…';validate(c,[name,'guest']);const [items,user]=await Promise.all([getItems(c),ensureAuth()]);let code;
    do{code=makeCode()}while((await get(ref(db,roomPath(code)))).exists());
    role='host';myId=user.uid;onlineHostUid=myId;currentRoomCode=code;state=fresh(gameConfig(c),[name],items);state.players[0].id=myId;state.players[0].avatar=currentAccountData?.account?.avatar||'';state.phase='lobby';history.replaceState({},'',urlFor('join',code));
    const roomRef=ref(db,roomPath(code)),publicRef=ref(db,`publicGames/${code}`);await set(roomRef,{hostUid:myId,createdAt:serverTimestamp(),state});await set(ref(db,roomPath(code,`members/${myId}`)),true);await set(ref(db,roomPath(code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(code,`presence/${myId}`))).remove();try{await set(publicRef,{hostUid:myId,updatedAt:serverTimestamp(),state:publicGameState(state)})}catch{console.info('Spectator directory is unavailable until the updated Firebase rules are published.')}saveOnlineSession('host',code,name);attachHost(code);if(pendingChallengeTarget){await set(ref(db,`gameInvites/${pendingChallengeTarget}/${myId}`),{fromUid:myId,fromName:name,room:code,createdAt:serverTimestamp()}).catch(()=>{});pendingChallengeTarget=null}renderLobby();
  }catch(e){alert(firebaseMessage(e));button.disabled=false;button.textContent='Create room'}
};
function attachHost(code){clearOnlineListeners();
  onlineUnsubs.push(onChildAdded(ref(db,roomPath(code,'joinRequests')),async snap=>{const id=snap.key,request=snap.val();if(!state.players.some(p=>p.id===id)&&state.phase==='lobby'&&state.players.length<8){state.players.push({id,name:String(request.name||'Player').slice(0,20),avatar:String(request.avatar||'').slice(0,4),budget:state.config.budget,picks:[],connected:true});await broadcast();renderLobby()}await remove(snap.ref)}));
  onlineUnsubs.push(onChildAdded(ref(db,roomPath(code,'actions')),async snap=>{const action=snap.val();if(state.phase==='playing')applyAction(snap.key,action.action,action.value);await remove(snap.ref)}));
  onlineUnsubs.push(onValue(ref(db,roomPath(code,'presence')),snap=>{if(!state)return;let changed=false;for(const p of state.players){if(p.id===myId)continue;const online=snap.child(p.id).exists();if(p.connected!==online){p.connected=online;changed=true;if(!online&&state.phase==='playing'&&state.config.bidMode==='open'&&state.auction&&!state.auction.passed.includes(p.id)){state.auction.passed.push(p.id);advanceAuction()}}}if(changed){broadcast();state.phase==='lobby'?renderLobby():render()}}));
}
$('#joinRoom').onclick=async()=>{
  const code=$('#joinCode').value.trim().toUpperCase(),name=$('#joinName').value.trim(),button=$('#joinRoom');
  if(code.length!==6||!name)return $('#joinError').textContent='Enter your name and six-character room code.';
  try{button.disabled=true;button.textContent='Joining…';$('#joinError').textContent='';const user=await ensureAuth(),roomRef=ref(db,roomPath(code)),snapshot=await get(roomRef);if(!snapshot.exists())throw Error('Room not found or host is offline.');const room=snapshot.val();if(Date.now()-(room.createdAt||0)>86400000)throw Error('This room has expired.');if(room.state?.phase!=='lobby')throw Error('This game has already started.');if((room.state?.players?.length||0)>=8)throw Error('Room is full.');
    role='guest';myId=user.uid;onlineHostUid=room.hostUid;currentRoomCode=code;history.replaceState({},'',urlFor('join',code));await set(ref(db,roomPath(code,`members/${myId}`)),true);await set(ref(db,roomPath(code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(code,`presence/${myId}`))).remove();await set(ref(db,roomPath(code,`joinRequests/${myId}`)),{name:name.slice(0,20),avatar:currentAccountData?.account?.avatar||'',joinedAt:serverTimestamp()});saveOnlineSession('guest',code,name);
    clearOnlineListeners();onlineUnsubs.push(onValue(ref(db,roomPath(code,'state')),snap=>{if(!snap.exists()){show('join');$('#joinError').textContent='The host closed this room.';return}state=hydrateState(snap.val());if(!state.players.some(p=>p.id===myId))return;state.phase==='lobby'?renderLobby():render()}));watchHostMigration(code,onlineHostUid);
  }catch(e){$('#joinError').textContent=firebaseMessage(e);button.disabled=false;button.textContent='Join room'}
};
function firebaseMessage(e){if(e.message?.includes('Room')||e.message?.includes('room')||e.message?.includes('game'))return e.message;if(e.code==='auth/admin-restricted-operation')return'Anonymous sign-in is not enabled in Firebase Authentication.';if(e.code==='PERMISSION_DENIED'||e.code==='permission-denied')return'Firebase blocked the request. Publish the included database rules.';return'Could not connect to Firebase. '+(e.message||'Check your connection.')}
async function broadcast(){if(role==='host'&&currentRoomCode){const publicState=publicGameState(state);await set(ref(db,roomPath(currentRoomCode,'state')),publicState);set(ref(db,`publicGames/${currentRoomCode}`),{hostUid:myId,updatedAt:serverTimestamp(),state:publicState}).catch(()=>{})}}
async function loadLiveGames(){show('spectate');$('#liveGames').innerHTML='<p class="muted">Loading active games…</p>';try{await ensureAuth();if(liveDirectoryUnsub)liveDirectoryUnsub();liveDirectoryUnsub=onValue(ref(db,'publicGames'),snap=>{const games=Object.entries(snap.val()||{}).filter(([,g])=>g.state?.phase!=='finished'&&Date.now()-(g.updatedAt||0)<86400000).sort((a,b)=>(b[1].updatedAt||0)-(a[1].updatedAt||0));$('#liveGames').innerHTML=games.length?games.map(([code,g])=>{const s=hydrateState(g.state),item=s.items?.[s.round];return`<article class="live-card"><div><span class="live-dot">LIVE</span><h3>Room ${esc(code)}</h3><p>${s.players.length} players · ${s.config?.bidMode==='open'?'Open Auction':'Blind Bid'} · ${s.phase==='lobby'?'Lobby':`Round ${s.round+1} of ${s.config?.rounds}`}</p>${item?`<small>Now drafting: ${esc(item.name)}</small>`:''}</div><button class="watchGame" data-room="${esc(code)}">Watch →</button></article>`}).join(''):'<div class="empty-live"><h3>No active games</h3><p class="muted">Create a room and it will appear here.</p></div>';$$('.watchGame',$('#liveGames')).forEach(b=>b.onclick=()=>watchGame(b.dataset.room))},()=>{$('#liveGames').innerHTML='<p class="error">Live games need the updated Firebase rules included with this build.</p>'})}catch(e){$('#liveGames').innerHTML=`<p class="error">${esc(firebaseMessage(e))}</p>`}}
async function watchGame(code,push=true){if(push)history.pushState({},'',urlFor('spectate',code));show('spectatorGame');$('#spectatorContent').innerHTML='<section class="card"><p class="muted">Connecting to live game…</p></section>';try{await ensureAuth();if(spectatorUnsub)spectatorUnsub();spectatorUnsub=onValue(ref(db,`publicGames/${code}`),snap=>{if(!snap.exists())return $('#spectatorContent').innerHTML='<section class="card"><h2>Game unavailable</h2><p>This room has ended or the host went offline.</p></section>';renderSpectator(code,hydrateState(snap.val().state))},()=>{$('#spectatorContent').innerHTML='<section class="card"><p class="error">Spectating needs the updated Firebase rules.</p></section>'})}catch(e){$('#spectatorContent').innerHTML=`<section class="card"><p class="error">${esc(firebaseMessage(e))}</p></section>`}}
function renderSpectator(code,s){const item=s.items?.[s.round],submitted=new Set(s.bidStatus||[]),waiting=s.players.filter(p=>p.connected!==false&&!submitted.has(p.id));let status='';if(s.phase==='lobby')status='<p class="spectator-callout">Waiting for the host to start.</p>';else if(s.phase==='finished')status='<p class="spectator-callout">Draft complete.</p>';else if(s.result){const winner=s.players.find(p=>p.id===s.result.winner);status=`<p class="spectator-callout">${winner?`${esc(winner.name)} won for $${s.result.amount}`:'No winner this round'}</p>`}else if(s.config?.bidMode==='open'){const high=s.players.find(p=>p.id===s.auction?.highBidder),turn=s.players.find(p=>p.id===s.auction?.turn);status=`<div class="spectator-auction"><span>High bid <b>$${s.auction?.highBid||0}</b>${high?` by ${esc(high.name)}`:''}</span><span>Playing now <b>${esc(turn?.name||'—')}</b></span></div>`}else status=`<p class="spectator-callout">Waiting for: <b>${waiting.length?waiting.map(p=>esc(p.name)).join(', '):'Reveal'}</b></p>`;$('#spectatorContent').innerHTML=`<section class="spectator-hero"><p class="eyebrow">SPECTATING · ROOM ${esc(code)}</p><small>${s.phase==='playing'?`Round ${s.round+1} of ${s.config?.rounds}`:s.phase}</small><h2>${esc(item?.name||'Waiting in lobby')}</h2><p>${esc(item?.sub||'')}</p>${item?.preview?`<audio class="preview" controls preload="none" src="${esc(item.preview)}"></audio>`:''}</section>${status}<div class="spectator-players">${s.players.map(p=>`<article><b>${esc(p.name)}</b><span>$${p.budget} left · ${(p.picks||[]).length} picks</span><small>${p.connected===false?'Offline':s.config?.bidMode==='blind'&&s.phase==='playing'&&!s.result?(submitted.has(p.id)?'Bid locked':'Choosing bid'):s.auction?.passed?.includes(p.id)?'Passed':'Active'}</small></article>`).join('')}</div>`}
function renderLobby(){show('lobby');$('#roomCode').textContent=currentRoomCode||'…';$('#inviteLink').value=inviteUrl(currentRoomCode);$('#connectionStatus').textContent=role==='host'?'Share the link or room code. Keep this tab open.':'Connected through Firebase — waiting for the host.';$('#lobbySettings').innerHTML=`<p><b>${state.config.bidMode==='open'?'Open Auction':'Blind Bid'}</b> · $${state.config.budget} budget · ${state.config.rounds} rounds</p>`;$('#lobbyPlayers').innerHTML=state.players.map(p=>`<span class="pill">${p.avatar?`${esc(p.avatar)} `:''}${esc(p.name)}</span>`).join('');$('#startOnline').classList.toggle('hidden',role!=='host');$('#startOnline').disabled=state.players.length<2;$('#lobbyHint').textContent=state.players.length<2?'Waiting for at least one more player…':''}
$('#startOnline').onclick=()=>{if(role==='host'&&state.players.length>=2){state.phase='playing';beginRound();broadcast();render()}};
function beginRound(){state.bids={};state.bidStatus=[];state.result=null;state.localIndex=0;state.localStep='handoff';if(state.config.bidMode==='open'){const eligible=state.players.filter(p=>p.connected!==false&&p.budget>0);state.auction={highBid:0,highBidder:null,passed:state.players.filter(p=>!eligible.includes(p)).map(p=>p.id),turn:eligible[0]?.id||null}}}
function current(){return state.items[state.round]} function player(id){return state.players.find(p=>p.id===id)}
function applyAction(id,action,value){if(state.result)return;const p=player(id);if(!p||p.connected===false)return;if(state.config.bidMode==='blind'){if(action!=='bid'||state.bids[id]!=null)return;const n=Number(value);if(!Number.isInteger(n)||n<0||n>p.budget)return;state.bids[id]=n;if(activePlayers().every(x=>state.bids[x.id]!=null))finishBlind()}else{const a=state.auction;if(a.turn!==id||a.passed.includes(id))return;if(action==='pass'){a.passed.push(id);advanceAuction()}else if(action==='bid'){const n=Number(value);if(!Number.isInteger(n)||n<=a.highBid||n>p.budget)return;a.highBid=n;a.highBidder=id;advanceAuction()}}broadcast();render()}
function activePlayers(){return state.players.filter(p=>p.connected!==false)}
function finishBlind(){const entries=activePlayers().map(p=>({p,b:state.bids[p.id]}));const max=Math.max(...entries.map(x=>x.b));const tied=entries.filter(x=>x.b===max);const ordered=[...state.players.slice(state.tieOffset),...state.players.slice(0,state.tieOffset)];const winner=ordered.find(p=>tied.some(x=>x.p.id===p.id));state.tieOffset=(state.players.indexOf(winner)+1)%state.players.length;award(winner,max,entries)}
function advanceAuction(){const a=state.auction,eligible=activePlayers().filter(p=>!a.passed.includes(p.id)&&p.budget>a.highBid);if(a.highBidder&&!a.passed.includes(a.highBidder)&&eligible.filter(p=>p.id!==a.highBidder).length===0)return award(player(a.highBidder),a.highBid,[]);if(!eligible.length){if(a.highBidder)return award(player(a.highBidder),a.highBid,[]);return award(null,0,[])}const start=state.players.findIndex(p=>p.id===a.turn);for(let n=1;n<=state.players.length;n++){const p=state.players[(start+n)%state.players.length];if(eligible.some(x=>x.id===p.id)&&p.id!==a.highBidder){a.turn=p.id;return}}if(a.highBidder)award(player(a.highBidder),a.highBid,[])}
function award(winner,amount,entries){if(winner){winner.budget-=amount;winner.picks.push({...current(),price:amount})}state.result={winner:winner?.id||null,amount,entries}}
function send(action,value){if(role==='guest'){if(action==='bid'){pendingBidRound=state.round;render()}set(ref(db,roomPath(currentRoomCode,`actions/${myId}`)),{action,value:value??null,nonce:crypto.randomUUID()}).catch(e=>{pendingBidRound=-1;render();alert(firebaseMessage(e))})}else applyAction(myId,action,value)}
function render(){if(!state)return; if(state.phase==='finished')return renderFinal();show('game');const item=current(),audio=$('#itemPreview');$('#roundLabel').textContent=`Round ${state.round+1} of ${state.config.rounds}`;$('#itemName').textContent=item.name;$('#itemSubtitle').textContent=item.sub||'';$('#itemArt').classList.toggle('hidden',!item.art);if(item.art)$('#itemArt').src=item.art;audio.classList.toggle('hidden',!item.preview);if(item.preview&&audio.src!==item.preview){audio.src=item.preview;audio.load()}if(!item.preview){audio.pause();audio.removeAttribute('src')}$('#scoreboard').innerHTML=state.players.map(p=>`<div class="score"><b>${esc(p.name)}</b><span>$${p.budget} left · ${p.picks.length} picks</span></div>`).join('');$('#actionCard').classList.toggle('hidden',Boolean(state.result));$('#resultsCard').classList.toggle('hidden',!state.result);if(state.result)return renderResult();state.config.bidMode==='blind'?renderBlind():renderAuction()}
function renderBlind(){const card=$('#actionCard'),submitted=new Set([...(state.bidStatus||[]),...Object.keys(state.bids||{})]);if(role==='guest'&&pendingBidRound===state.round)submitted.add(myId);const waiting=activePlayers().filter(p=>!submitted.has(p.id)),status=`<div class="waiting-panel"><b>${waiting.length?'Waiting for bids from':'All bids locked'}</b><div>${waiting.length?waiting.map(p=>`<span>${esc(p.name)}</span>`).join(''):'<span>Ready to reveal</span>'}</div></div>`;$('#scoreboard').innerHTML=state.players.map(p=>`<div class="score"><b>${esc(p.name)}</b><span>$${p.budget} left · ${submitted.has(p.id)?'Bid locked':'Choosing bid'}</span></div>`).join('');if(role==='local'){const p=state.players[state.localIndex];if(state.localStep==='handoff'){card.innerHTML=`<h3>Pass to ${esc(p.name)}</h3><p>Tap when only ${esc(p.name)} can see the screen.</p>${status}<button class="primary" id="ready">I’m ready</button>`;$('#ready').onclick=()=>{state.localStep='bid';render()}}else{card.innerHTML=bidForm(p,0,'Lock secret bid');bindBid(p.id,true)}}else{const p=player(myId),done=submitted.has(myId);card.innerHTML=done?`<h3>Bid locked</h3><p>Your amount is saved and remains secret.</p>${status}`:bidForm(p,0,'Lock secret bid');if(!done)bindBid(p.id,false)}}
function bidForm(p,min,label){return`<h3>${esc(p.name)}’s bid</h3><p>Available: $${p.budget}</p><div class="bidbox"><div><label>Choose your bid</label><div class="bid-stepper"><button id="bidMinus" type="button" aria-label="Decrease bid">−</button><output id="bidDisplay">$${min}</output><button id="bidPlus" type="button" aria-label="Increase bid">+</button><input id="bidValue" type="hidden" value="${min}"></div></div><button id="bidBtn">${label}</button></div><p id="bidError" class="error"></p>`}
function bindStepper(min,max){const input=$('#bidValue'),display=$('#bidDisplay'),minus=$('#bidMinus'),plus=$('#bidPlus');const update=n=>{n=Math.max(min,Math.min(max,n));input.value=n;display.textContent=`$${n}`;minus.disabled=n<=min;plus.disabled=n>=max};minus.onclick=()=>update(Number(input.value)-1);plus.onclick=()=>update(Number(input.value)+1);update(min)}
function bindBid(id,local){const p=player(id);bindStepper(0,p.budget);$('#bidBtn').onclick=()=>{const n=Number($('#bidValue').value);if(!Number.isInteger(n)||n<0||n>p.budget)return $('#bidError').textContent=`Enter a whole dollar amount from $0 to $${p.budget}.`;if(local){state.bids[id]=n;state.localIndex++;if(state.localIndex>=state.players.length)finishBlind();else state.localStep='handoff';render()}else send('bid',n)}}
function renderAuction(){const a=state.auction,turn=player(a.turn),high=a.highBidder?player(a.highBidder):null;$('#scoreboard').innerHTML=state.players.map(p=>`<div class="score ${p.id===a.turn?'turn':''}"><b>${esc(p.name)}</b><span>$${p.budget} left ${a.passed.includes(p.id)?'· Passed':''}</span></div>`).join('');const card=$('#actionCard');card.innerHTML=`<div class="auction"><p>Current bid</p><strong>$${a.highBid}</strong><p>${high?`by ${esc(high.name)}`:'No bids yet'}</p></div><div id="turnAction"></div>`;const act=$('#turnAction');if(role==='local'){const p=turn;act.innerHTML=`<h3>Pass to ${esc(p.name)}</h3><p>All auction activity is visible.</p><button id="localReady" class="primary">Take my turn</button>`;$('#localReady').onclick=()=>renderAuctionControls(p)}else if(myId===a.turn)renderAuctionControls(player(myId));else act.innerHTML=`<p class="muted">Waiting for ${esc(turn?.name||'the next player')}…</p>`}
function renderAuctionControls(p){const act=$('#turnAction'),min=state.auction.highBid+1;act.innerHTML=`<h3>${esc(p.name)}, your turn</h3>${bidForm(p,min,'Place bid')}<button id="passBtn">Pass for this item</button>`;bindStepper(min,p.budget);$('#bidBtn').onclick=()=>{const n=Number($('#bidValue').value);if(!Number.isInteger(n)||n<min||n>p.budget)return $('#bidError').textContent=`Bid a whole dollar amount from $${min} to $${p.budget}.`;if(role==='local')applyAction(p.id,'bid',n);else send('bid',n)};$('#passBtn').onclick=()=>role==='local'?applyAction(p.id,'pass'):send('pass')}
function renderResult(){const r=state.result,w=r.winner?player(r.winner):null,card=$('#resultsCard');$('#actionCard').classList.add('hidden');card.innerHTML=`<h3>${w?`<span class="winner">${esc(w.name)}</span> wins ${esc(current().name)} for $${r.amount}`:`No one drafted ${esc(current().name)}`}</h3>${r.entries?.length?'<div>'+r.entries.sort((a,b)=>b.b-a.b).map(x=>`<div class="result-row">${esc(x.p.name)} <b>$${x.b}</b></div>`).join('')+'</div>':''}${(role==='host'||role==='local')?'<button id="nextRound" class="primary">'+(state.round+1>=state.config.rounds?'See final lineups':'Next round')+'</button>':'<p class="muted">Waiting for the host…</p>'}`;const b=$('#nextRound');if(b)b.onclick=()=>{state.round++;$('#actionCard').classList.remove('hidden');if(state.round>=state.config.rounds)state.phase='finished';else beginRound();broadcast();render()}}
function renderFinal(){show('final');const winner=state.matchWinner?player(state.matchWinner):null,canChoose=role==='host'||role==='local';$('#finalResults').innerHTML=`${winner?`<div class="champion-banner"><span>🏆</span><div><small>MATCH WINNER</small><h2>${winner.avatar?`${esc(winner.avatar)} `:''}${esc(winner.name)}</h2></div></div>`:canChoose?'<div class="winner-prompt"><h3>Who built the best lineup?</h3><p>Choose the match winner to save everyone’s result.</p></div>':'<p class="spectator-callout">Waiting for the host to choose the match winner…</p>'}<div class="final-lineups">${state.players.map(p=>`<article class="final-player ${p.id===state.matchWinner?'is-champion':''}"><h3>${p.avatar?`${esc(p.avatar)} `:''}${esc(p.name)} · $${p.budget} left</h3>${p.picks.length?p.picks.map(x=>`<p>${esc(x.name)} — $${x.price}</p>`).join(''):'<p class="muted">No picks</p>'}${!winner&&canChoose?`<button class="chooseWinner" data-player="${esc(p.id)}">Crown ${esc(p.name)}</button>`:''}</article>`).join('')}</div>${winner?`<div class="final-actions">${canChoose?'<button id="rematch" class="primary">Rematch</button>':'<span class="muted">The host can start a rematch.</span>'}<button id="newGame">Home</button></div>`:''}`;$$('.chooseWinner',$('#finalResults')).forEach(b=>b.onclick=()=>{state.matchWinner=b.dataset.player;if(role==='host')broadcast();renderFinal();recordCompletedGame()});const newGame=$('#newGame');if(newGame)newGame.onclick=()=>{clearSavedSession();location.href=urlFor('home').href};const rematch=$('#rematch');if(rematch)rematch.onclick=()=>startRematch();if(winner)recordCompletedGame()}
async function recordCompletedGame(){const user=auth.currentUser;if(!state?.matchWinner||!state.gameId||!user||user.isAnonymous||recordedGames.has(state.gameId)||!state.players.some(p=>p.id===user.uid))return;recordedGames.add(state.gameId);const me=state.players.find(p=>p.id===user.uid),won=state.matchWinner===user.uid,completedAt=Date.now(),mode=state.config.bidMode==='open'?'Open Auction':'Blind Bid';try{const result=await runTransaction(ref(db,`users/${user.uid}`),data=>{data??={};data.history??={};if(data.history[state.gameId])return data;data.stats??={games:0,wins:0,losses:0,itemsWon:0};data.stats.games=(data.stats.games||0)+1;data.stats.wins=(data.stats.wins||0)+(won?1:0);data.stats.losses=(data.stats.losses||0)+(won?0:1);data.stats.itemsWon=(data.stats.itemsWon||0)+(me.picks?.length||0);data.history[state.gameId]={completedAt,won,mode,players:state.players.map(p=>p.name),itemsWon:me.picks?.length||0};const keys=Object.keys(data.history).sort((a,b)=>(data.history[b].completedAt||0)-(data.history[a].completedAt||0));keys.slice(20).forEach(k=>delete data.history[k]);return data});currentAccountData=result.snapshot.val();const account=currentAccountData.account||{},username=account.username||accountName(user),avatar=account.avatar||avatarOptions[0];await set(ref(db,`publicProfiles/${user.uid}`),{username,avatar,stats:currentAccountData.stats||{},updatedAt:serverTimestamp()});renderCareer(currentAccountData.stats||{});renderHistory(currentAccountData.history||{})}catch(e){recordedGames.delete(state.gameId);console.warn('Could not save game history.',e)}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

// Phases 5–8: universal taste profiles, matchmaking, social play,
// reconnection, achievements, rematches, and installable-app polish.
function splitTaste(value){return[...new Set(String(value||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20))]}
function renderTaste(){const taste=currentAccountData?.preferences||{};$('#tasteArtists').value=(taste.artists||[]).join(', ');$('#tasteGenres').value=(taste.genres||[]).join(', ')}
$('#tasteForm').onsubmit=async e=>{e.preventDefault();const user=auth.currentUser;if(!user||user.isAnonymous)return $('#tasteNotice').textContent='Sign in to save matchmaking preferences.';const preferences={artists:splitTaste($('#tasteArtists').value),genres:splitTaste($('#tasteGenres').value),updatedAt:Date.now()};try{await set(ref(db,`users/${user.uid}/preferences`),preferences);currentAccountData??={};currentAccountData.preferences=preferences;$('#tasteNotice').className='success';$('#tasteNotice').textContent='Music taste saved. You can now use matchmaking.'}catch(err){$('#tasteNotice').className='error';$('#tasteNotice').textContent=firebaseMessage(err)}};
function combinedTaste(){const manual=currentAccountData?.preferences||{},spotify=currentAccountData?.musicProfile||{};return{artists:[...new Set([...(manual.artists||[]),...(spotify.topArtists||[]).map(x=>x.name)].map(x=>x.toLowerCase()))].slice(0,30),genres:[...new Set([...(manual.genres||[]),...(spotify.topArtists||[]).flatMap(x=>x.genres||[])].map(x=>x.toLowerCase()))].slice(0,30),spotify:Boolean(spotify.spotifyId)}}
function compatibility(a,b){const aa=new Set(a.artists||[]),ag=new Set(a.genres||[]),sharedArtists=(b.artists||[]).filter(x=>aa.has(x)),sharedGenres=(b.genres||[]).filter(x=>ag.has(x));const total=Math.max(4,new Set([...(a.artists||[]),...(b.artists||[]),...(a.genres||[]),...(b.genres||[])]).size),score=Math.min(99,Math.round((sharedArtists.length*3+sharedGenres.length)*100/total));return{score,sharedArtists,sharedGenres}}
async function loadCommunity(){const user=await ensureAuth();if(!user||user.isAnonymous){$('#matchStatus').className='muted';$('#matchStatus').textContent='Sign in to use matchmaking and friends.';$('#matchSuggestions').innerHTML='';$('#friendRequests').innerHTML='';$('#friendsList').innerHTML='';return loadLeaderboard()}await Promise.all([renderMatchmaking(),loadFriends(),loadLeaderboard(),loadGameInvites()])}
async function renderMatchmaking(){const user=auth.currentUser;if(!user||user.isAnonymous)return;const snap=await get(ref(db,'matchmaking')),entries=snap.val()||{},mine=entries[user.uid],taste=combinedTaste();$('#toggleMatchmaking').textContent=mine?'Leave matchmaking':'Join matchmaking';const ranked=Object.entries(entries).filter(([uid,x])=>uid!==user.uid&&Date.now()-(x.updatedAt||0)<3600000).map(([uid,x])=>({uid,...x,...compatibility(taste,x.taste||{})})).sort((a,b)=>b.score-a.score).slice(0,8);$('#matchStatus').className=mine?'success':'muted';$('#matchStatus').textContent=mine?`You’re visible to compatible players${taste.spotify?' with Spotify-enhanced matching':', using your saved preferences'}.`:'Join the queue to appear to other players.';$('#matchSuggestions').innerHTML=ranked.length?`<h4>Compatible players</h4>${ranked.map(x=>`<article class="match-row"><span class="match-score">${x.score}%</span><div><b>${esc(x.avatar||'🎵')} ${esc(x.name||'Player')}</b><small>${x.sharedArtists.length?`Both like ${esc(x.sharedArtists.slice(0,3).join(', '))}`:x.sharedGenres.length?`Shared genres: ${esc(x.sharedGenres.slice(0,3).join(', '))}`:'Ready for a fresh matchup'}</small></div><button class="challengePlayer smallbtn" data-uid="${esc(x.uid)}">Challenge</button></article>`).join('')}`:'<p class="muted">No other players are in the queue yet. Invite a friend to join matchmaking.</p>';$$('.challengePlayer',$('#matchSuggestions')).forEach(button=>button.onclick=()=>prepareChallenge(button.dataset.uid,entries[button.dataset.uid]))}
$('#toggleMatchmaking').onclick=async()=>{const user=auth.currentUser;if(!user||user.isAnonymous){navigate('account');return}const own=ref(db,`matchmaking/${user.uid}`),snap=await get(own);if(snap.exists())await remove(own);else{const taste=combinedTaste();if(!taste.artists.length&&!taste.genres.length){navigate('account');$('#tasteNotice').textContent='Add at least one artist or genre before joining matchmaking.';return}const name=currentAccountData?.account?.username||accountName(user),avatar=currentAccountData?.account?.avatar||'🎵';await set(own,{name,avatar,taste,updatedAt:Date.now()});await onDisconnect(own).remove()}renderMatchmaking().catch(()=>{})};
function prepareChallenge(uid,entry){pendingChallengeTarget=uid;navigate('host');const root=$('#hostForm .setup');const mine=combinedTaste(),theirs=entry?.taste||{},shared=(theirs.artists||[]).filter(x=>mine.artists.includes(x)).slice(0,4);if(shared.length){const box=root.querySelector('.artists');box.innerHTML='';shared.forEach(x=>addArtist(box,x.replace(/\b\w/g,c=>c.toUpperCase())))}$('#hostName').focus()}
async function loadGameInvites(){const user=auth.currentUser;if(!user||user.isAnonymous)return;const snap=await get(ref(db,`gameInvites/${user.uid}`)),invites=Object.entries(snap.val()||{}).filter(([,x])=>x.room&&Date.now()-(x.createdAt||0)<86400000);if(!invites.length)return;$('#matchSuggestions').insertAdjacentHTML('afterbegin',`<div class="invite-stack"><h4>Game invitations</h4>${invites.map(([uid,x])=>`<article><b>${esc(x.fromName||'A player')} challenged you</b><button class="acceptInvite smallbtn" data-from="${esc(uid)}" data-room="${esc(x.room)}">Join ${esc(x.room)}</button></article>`).join('')}</div>`);$$('.acceptInvite',$('#matchSuggestions')).forEach(b=>b.onclick=async()=>{await remove(ref(db,`gameInvites/${user.uid}/${b.dataset.from}`));$('#joinCode').value=b.dataset.room;$('#joinName').value=currentAccountData?.account?.username||accountName(user);navigate('join')})}
$('#friendSearchForm').onsubmit=async e=>{e.preventDefault();const user=auth.currentUser,query=$('#friendSearch').value.trim().toLowerCase();if(!user||user.isAnonymous)return navigate('account');try{const snap=await get(ref(db,'publicProfiles')),match=Object.entries(snap.val()||{}).find(([uid,p])=>uid!==user.uid&&String(p.username||'').toLowerCase()===query);if(!match)throw Error('No player has that exact username.');const [target]=match;await set(ref(db,`friendRequests/${target}/${user.uid}`),{fromUid:user.uid,name:currentAccountData?.account?.username||accountName(user),avatar:currentAccountData?.account?.avatar||'🎵',createdAt:Date.now()});$('#friendNotice').className='success';$('#friendNotice').textContent='Friend request sent.'}catch(err){$('#friendNotice').className='error';$('#friendNotice').textContent=err.message}};
async function loadFriends(){const user=auth.currentUser;if(!user||user.isAnonymous)return;const [requestSnap,friendSnap]=await Promise.all([get(ref(db,`friendRequests/${user.uid}`)),get(ref(db,`friends/${user.uid}`))]),requests=requestSnap.val()||{},friends=friendSnap.val()||{};$('#friendRequests').innerHTML=Object.keys(requests).length?`<h4>Requests</h4>${Object.entries(requests).map(([uid,x])=>`<article class="friend-row"><span>${esc(x.avatar||'🎵')} <b>${esc(x.name||'Player')}</b></span><button class="acceptFriend smallbtn" data-uid="${esc(uid)}">Accept</button></article>`).join('')}`:'';$('#friendsList').innerHTML=`<h4>Friends</h4>${Object.entries(friends).length?Object.entries(friends).map(([uid,x])=>`<article class="friend-row"><span>${esc(x.avatar||'🎵')} <b>${esc(x.name||'Player')}</b></span><button class="friendChallenge smallbtn" data-uid="${esc(uid)}">Challenge</button></article>`).join(''):'<p class="muted">Add friends by their exact username.</p>'}`;$$('.acceptFriend',$('#friendRequests')).forEach(b=>b.onclick=async()=>{const request=requests[b.dataset.uid],me={name:currentAccountData?.account?.username||accountName(user),avatar:currentAccountData?.account?.avatar||'🎵',since:Date.now()};await set(ref(db,`friends/${b.dataset.uid}/${user.uid}`),me);await set(ref(db,`friends/${user.uid}/${b.dataset.uid}`),{name:request.name,avatar:request.avatar||'🎵',since:Date.now()});await remove(ref(db,`friendRequests/${user.uid}/${b.dataset.uid}`));loadFriends()});$$('.friendChallenge',$('#friendsList')).forEach(b=>b.onclick=()=>prepareChallenge(b.dataset.uid,{taste:{}}))}
async function loadLeaderboard(){try{const snap=await get(ref(db,'publicProfiles')),players=Object.entries(snap.val()||{}).map(([uid,p])=>({uid,...p,games:p.stats?.games||0,wins:p.stats?.wins||0})).sort((a,b)=>b.wins-a.wins||(b.games?b.wins/b.games:0)-(a.games?a.wins/a.games:0)).slice(0,25);$('#leaderboard').innerHTML=players.length?players.map((p,i)=>`<article class="leader-row"><span class="rank">${i+1}</span><span class="leader-avatar">${esc(p.avatar||'🎵')}</span><div><b>${esc(p.username||'Draft player')}</b><small>${p.games} games · ${p.games?Math.round(p.wins/p.games*100):0}% win rate</small></div><strong>${p.wins} wins</strong></article>`).join(''):'<p class="muted">No ranked players yet.</p>'}catch{$('#leaderboard').innerHTML='<p class="error">Publish the newest Firebase rules to load the leaderboard.</p>'}}
$('#refreshCommunity').onclick=()=>loadCommunity();
function renderAchievements(stats){const achievements=[['First Draft',(stats.games||0)>=1,'Complete a game'],['Auction Ace',(stats.wins||0)>=1,'Win your first duel'],['Collector',(stats.itemsWon||0)>=10,'Draft 10 items'],['Veteran',(stats.games||0)>=10,'Play 10 games'],['Champion',(stats.wins||0)>=10,'Win 10 games']];$('#achievementList').innerHTML='<h4>Achievements</h4>'+achievements.map(([name,unlocked,hint])=>`<span class="achievement ${unlocked?'unlocked':''}" title="${esc(hint)}">${unlocked?'✓':'○'} ${esc(name)}</span>`).join('')}
function sessionKey(){return'draftDuelActiveSession'}
function saveOnlineSession(savedRole,code,name){localStorage.setItem(sessionKey(),JSON.stringify({role:savedRole,code,name,uid:auth.currentUser?.uid,updatedAt:Date.now()}))}
function clearSavedSession(){localStorage.removeItem(sessionKey())}
async function resumeOnlineSession(){const saved=JSON.parse(localStorage.getItem(sessionKey())||'null'),user=auth.currentUser;if(!saved||!user||saved.uid!==user.uid||Date.now()-saved.updatedAt>86400000)return;const roomSnap=await get(ref(db,roomPath(saved.code)));if(!roomSnap.exists()){clearSavedSession();return}const room=roomSnap.val();currentRoomCode=saved.code;myId=user.uid;onlineHostUid=room.hostUid;state=hydrateState(room.state);await set(ref(db,roomPath(saved.code,`members/${myId}`)),true);if(room.hostUid===user.uid){role='host';await set(ref(db,roomPath(saved.code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(saved.code,`presence/${myId}`))).remove();attachHost(saved.code)}else if(state.players.some(p=>p.id===user.uid)){role='guest';await set(ref(db,roomPath(saved.code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(saved.code,`presence/${myId}`))).remove();clearOnlineListeners();onlineUnsubs.push(onValue(ref(db,roomPath(saved.code,'state')),snap=>{if(!snap.exists()){clearSavedSession();return}state=hydrateState(snap.val());state.phase==='lobby'?renderLobby():render()}));watchHostMigration(saved.code,onlineHostUid)}else{clearSavedSession();return}state.phase==='lobby'?renderLobby():render()}
function watchHostMigration(code,hostUid){onlineUnsubs.push(onValue(ref(db,roomPath(code,`presence/${hostUid}`)),snap=>{clearTimeout(hostMigrationTimer);if(snap.exists()||role!=='guest')return;hostMigrationTimer=setTimeout(()=>claimHost(code,hostUid),10000)}))}
async function claimHost(code,expectedHost){if(role!=='guest'||!state?.players.some(p=>p.id===myId))return;try{const result=await runTransaction(ref(db,roomPath(code)),room=>{if(!room||room.hostUid!==expectedHost||room.presence?.[expectedHost]||room.members?.[myId]!==true)return;room.hostUid=myId;return room});if(!result.committed||result.snapshot.val()?.hostUid!==myId)return;role='host';onlineHostUid=myId;await set(ref(db,roomPath(code,`presence/${myId}`)),{online:true});await onDisconnect(ref(db,roomPath(code,`presence/${myId}`))).remove();attachHost(code);saveOnlineSession('host',code,player(myId)?.name||'Host');await broadcast();state.phase==='lobby'?renderLobby():render()}catch(e){console.info('Host migration was not available.',e)}}
async function startRematch(){if(role==='guest')return;if(role==='local'){const names=state.players.map(p=>p.name),items=shuffle(state.items);state=fresh(state.config,names,items);localNames=state.players.map(x=>x.id);beginRound();render();return}if(role==='host'){const old=state,items=shuffle(old.items),players=old.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar||'',budget:old.config.budget,picks:[],connected:p.connected!==false}));state=fresh(old.config,[],items);state.players=players;state.phase='lobby';await broadcast();renderLobby()}}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installApp').classList.remove('hidden')});
$('#installApp').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installApp').classList.add('hidden')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
