const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={role:null,roomCode:'',peer:null,hostConn:null,connections:new Map(),myId:crypto.randomUUID(),mode:'artist',pool:[],game:null,localBidIndex:0};
const MAX_PLAYERS=8;

const SPOTIFY_AUTH_URL='https://accounts.spotify.com/authorize',SPOTIFY_TOKEN_URL='https://accounts.spotify.com/api/token',SPOTIFY_SCOPES='playlist-read-private playlist-read-collaborative';
function spotifyRedirectUri(){return `${location.origin}${location.pathname}`}
function randomString(n=64){const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',b=crypto.getRandomValues(new Uint8Array(n));return [...b].map(x=>c[x%c.length]).join('')}
function base64Url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(v){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))}
function spotifyTokens(){try{return JSON.parse(localStorage.getItem('draftDuelSpotifyTokens')||'null')}catch{return null}}
function saveSpotifyTokens(t){const p=spotifyTokens()||{},s={...p,...t,expires_at:Date.now()+((t.expires_in||3600)*1000)-30000};localStorage.setItem('draftDuelSpotifyTokens',JSON.stringify(s));updateSpotifyUi();return s}
function clearSpotifyTokens(){localStorage.removeItem('draftDuelSpotifyTokens');updateSpotifyUi()}
function updateSpotifyUi(msg=''){const e=$('#spotifyStatus');if(!e)return;const ok=!!spotifyTokens()?.access_token;e.textContent=msg||(ok?'Spotify connected. Paste a playlist URL and import it.':'Spotify is not connected.');e.className=`status ${ok?'ok':''}`;$('#spotifyConnectBtn').textContent=ok?'Reconnect Spotify':'Connect Spotify';$('#spotifyDisconnectBtn').hidden=!ok}
async function connectSpotify(){const id=$('#spotifyClientId').value.trim();if(!id)return updateSpotifyUi('Paste your Spotify Client ID first.');localStorage.setItem('draftDuelSpotifyClientId',id);const verifier=randomString(96),challenge=base64Url(await sha256(verifier)),oauthState=randomString(32);sessionStorage.setItem('spotifyCodeVerifier',verifier);sessionStorage.setItem('spotifyOAuthState',oauthState);location.assign(`${SPOTIFY_AUTH_URL}?${new URLSearchParams({client_id:id,response_type:'code',redirect_uri:spotifyRedirectUri(),scope:SPOTIFY_SCOPES,code_challenge_method:'S256',code_challenge:challenge,state:oauthState,show_dialog:'true'})}`)}
async function exchangeSpotifyCode(code){const verifier=sessionStorage.getItem('spotifyCodeVerifier'),clientId=localStorage.getItem('draftDuelSpotifyClientId');if(!verifier||!clientId)throw Error('Spotify login session expired.');const r=await fetch(SPOTIFY_TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,grant_type:'authorization_code',code,redirect_uri:spotifyRedirectUri(),code_verifier:verifier})}),d=await r.json();if(!r.ok)throw Error(d.error_description||'Spotify login failed.');saveSpotifyTokens(d)}
async function spotifyAccessToken(){let t=spotifyTokens();if(!t?.access_token)throw Error('Connect Spotify first.');if(t.expires_at>Date.now())return t.access_token;if(!t.refresh_token)throw Error('Spotify session expired.');const r=await fetch(SPOTIFY_TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:localStorage.getItem('draftDuelSpotifyClientId'),grant_type:'refresh_token',refresh_token:t.refresh_token})}),d=await r.json();if(!r.ok){clearSpotifyTokens();throw Error('Spotify session expired.')}return saveSpotifyTokens(d).access_token}
async function handleSpotifyCallback(){const p=new URLSearchParams(location.search),code=p.get('code');if(!code&&!p.get('error'))return;history.replaceState({},'',spotifyRedirectUri());if(p.get('error'))return updateSpotifyUi('Spotify connection cancelled.');if(p.get('state')!==sessionStorage.getItem('spotifyOAuthState'))return updateSpotifyUi('Spotify security check failed.');try{await exchangeSpotifyCode(code);updateSpotifyUi('Spotify connected successfully.')}catch(e){updateSpotifyUi(e.message)}}

const gameCatalog=[['Minecraft','Mojang'],['Grand Theft Auto V','Rockstar Games'],['The Last of Us','Naughty Dog'],['Red Dead Redemption 2','Rockstar Games'],['Fortnite','Epic Games'],['God of War','Santa Monica Studio'],['EA Sports FC 25','EA Sports'],['Call of Duty: Black Ops II','Treyarch'],['Elden Ring','FromSoftware'],['Mario Kart 8 Deluxe','Nintendo'],['Marvel’s Spider-Man','Insomniac Games'],['Rocket League','Psyonix']].map((x,i)=>({id:'g'+i,title:x[0],subtitle:x[1],art:'',preview:''}));
function switchView(id){$$('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function setStatus(t,type=''){const e=$('#poolStatus');e.textContent=t;e.className='status '+type}
function setJoinStatus(t,type=''){const e=$('#joinStatus');e.textContent=t;e.className='status '+type}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function roomPeerId(code){return `draft-duel-${code.toLowerCase()}`}
const PEER_OPTIONS={host:'0.peerjs.com',port:443,path:'/',secure:true,debug:1,config:{iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}],sdpSemantics:'unified-plan'}};
function makePeer(id){return id?new Peer(id,PEER_OPTIONS):new Peer(PEER_OPTIONS)}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',b=crypto.getRandomValues(new Uint8Array(6));return [...b].map(x=>chars[x%chars.length]).join('')}
function placeholder(t){return `https://placehold.co/600x600/7857ff/ffffff?text=${encodeURIComponent(t.slice(0,18))}`}
function currentLocalPlayer(){return state.role==='local'?state.game?.players[state.localBidIndex]:null}
function myPlayer(){return state.role==='local'?currentLocalPlayer():state.game?.players.find(p=>p.id===state.myId)}
function publicSnapshot(){const g=state.game;return{type:'snapshot',roomCode:state.roomCode,game:{phase:g.phase,settings:g.settings,players:g.players,queue:g.queue,round:g.round,locked:Object.keys(g.bids||{}),roundResult:g.roundResult||null}}}
function broadcast(msg=publicSnapshot()){for(const c of state.connections.values())if(c.open)c.send(msg)}
function sendToHost(msg){if(state.hostConn?.open)state.hostConn.send(msg)}

function startPassPlay(){state.role='local';state.roomCode='';state.localBidIndex=0;document.body.classList.remove('is-guest');document.body.classList.add('is-local');state.game={phase:'lobby',settings:{},players:[{id:'local-'+crypto.randomUUID(),name:'Player 1',money:20,picks:[],connected:true,host:false},{id:'local-'+crypto.randomUUID(),name:'Player 2',money:20,picks:[],connected:true,host:false}],queue:[],round:0,bids:{},roundResult:null};renderLobby();switchView('#lobbyView')}
function addLocalPlayer(){if(state.role!=='local')return;const input=$('#localPlayerName'),name=input.value.trim()||`Player ${state.game.players.length+1}`;if(state.game.players.length>=MAX_PLAYERS)return;state.game.players.push({id:'local-'+crypto.randomUUID(),name,money:20,picks:[],connected:true,host:false});input.value='';renderLobby()}
function removeLocalPlayer(id){if(state.role!=='local'||state.game.players.length<=2)return;state.game.players=state.game.players.filter(p=>p.id!==id);renderLobby()}
function showPassDialog(){if(state.role!=='local'||state.game.phase!=='playing')return;const p=currentLocalPlayer();if(!p)return;$('#passDialogTitle').textContent=`${p.name}'s turn`;$('#passDialogText').textContent=`Pass the device to ${p.name}. Tap ready when nobody else can see the screen.`;$('#passDialog').showModal()}
function localSubmitBid(){const p=currentLocalPlayer();if(!p||state.game.phase!=='playing'||state.game.bids[p.id]!==undefined)return;const bid=Math.max(0,Math.min(p.money,+$('#bidInput').value||0));state.game.bids[p.id]=bid;state.localBidIndex++;$('#bidInput').value=1;if(state.localBidIndex>=state.game.players.length){resolveRound()}else{renderGame();showPassDialog()}}

function createRoom(){const name=$('#hostName').value.trim()||'Host';state.role='host';state.roomCode=makeCode();document.body.classList.remove('is-guest','is-local');state.game={phase:'lobby',settings:{},players:[{id:state.myId,name,money:20,picks:[],connected:true,host:true}],queue:[],round:0,bids:{},roundResult:null};const peer=makePeer(roomPeerId(state.roomCode));state.peer=peer;peer.on('open',()=>{renderLobby();switchView('#lobbyView')});peer.on('connection',conn=>{conn.on('data',msg=>hostHandleMessage(conn,msg));conn.on('close',()=>hostDisconnect(conn));conn.on('error',()=>hostDisconnect(conn))});peer.on('error',e=>{alert(`Could not create room: ${e.type||e.message}`);leaveRoom()})}
function joinRoom(){const name=$('#joinName').value.trim(),code=$('#joinCode').value.trim().toUpperCase();if(!name)return setJoinStatus('Enter your name.','error');if(!/^[A-Z2-9]{6}$/.test(code))return setJoinStatus('Enter a valid six-character room code.','error');setJoinStatus('Connecting…');state.role='guest';state.roomCode=code;document.body.classList.remove('is-local');document.body.classList.add('is-guest');const peer=makePeer();state.peer=peer;peer.on('open',()=>{const c=peer.connect(roomPeerId(code),{reliable:true});state.hostConn=c;c.on('open',()=>c.send({type:'join',player:{id:state.myId,name}}));c.on('data',guestHandleMessage);c.on('close',()=>connectionLost());c.on('error',()=>connectionLost());setTimeout(()=>{if(!c.open)setJoinStatus('Room not found or host is offline.','error')},7000)});peer.on('error',e=>{if(e.type==='peer-unavailable')setJoinStatus('That room is not registered with the host service. Check the code and make sure the host still has the room open.','error');else if(e.type==='network'||e.type==='server-error'||e.type==='socket-error')setJoinStatus('Could not reach the online room service. Try another network or disable a restrictive VPN/firewall.','error');else setJoinStatus(`Online connection error: ${e.type||e.message}`,'error')});peer.on('disconnected',()=>{try{peer.reconnect()}catch{}})}
function hostHandleMessage(conn,msg){if(msg.type==='join'){if(state.game.players.length>=MAX_PLAYERS){conn.send({type:'error',message:'This room is full.'});return conn.close()}if(state.game.phase!=='lobby'){conn.send({type:'error',message:'This game has already started.'});return conn.close()}const existing=state.game.players.find(p=>p.id===msg.player.id);if(existing){existing.connected=true}else state.game.players.push({...msg.player,money:20,picks:[],connected:true,host:false});state.connections.set(msg.player.id,conn);conn.metadata={playerId:msg.player.id};broadcast();renderLobby()}else if(msg.type==='bid')hostReceiveBid(msg.playerId,msg.bid)}
function guestHandleMessage(msg){if(msg.type==='error'){setJoinStatus(msg.message,'error');state.hostConn?.close();return}if(msg.type==='snapshot'){state.roomCode=msg.roomCode;state.game=msg.game;renderFromSnapshot()}}
function hostDisconnect(conn){const id=conn.metadata?.playerId;if(!id)return;const p=state.game.players.find(x=>x.id===id);if(!p)return;p.connected=false;state.connections.delete(id);if(state.game.phase==='lobby')state.game.players=state.game.players.filter(x=>x.id!==id);else if(state.game.phase==='playing'&&!state.game.bids[id])state.game.bids[id]=0;broadcast();renderFromSnapshot();if(state.game.phase==='playing')checkAllBids()}
function connectionLost(){alert('Connection to the host was lost.');leaveRoom()}
function leaveRoom(){try{state.peer?.destroy()}catch{}state.connections.clear();state.peer=null;state.hostConn=null;state.game=null;state.role=null;state.roomCode='';state.localBidIndex=0;document.body.classList.remove('is-guest','is-local');switchView('#homeView')}

function renderLobby(){if(!state.game)return;$('#copyRoomCode').textContent=state.roomCode||'PASS & PLAY';$('#playerCount').textContent=`${state.game.players.length}/${MAX_PLAYERS}`;$('#lobbyRoleText').textContent=state.role==='local'?'Add everyone who is playing, then choose the draft settings.':state.role==='host'?'Share this code, then choose the draft settings.':'You are connected. Waiting for the host to start.';$('#lobbyHint').textContent=state.role==='local'?'One device, private turn-by-turn bidding.':'Players can join from phones, tablets, or computers. The host must keep this tab open.';$('#lobbyPlayers').innerHTML=state.game.players.map(p=>`<div class="lobby-player"><div class="identity"><span class="avatar">${escapeHtml(p.name[0]||'?')}</span><strong>${escapeHtml(p.name)}</strong></div><div>${p.host&&state.role!=='local'?'<span class="host-badge">HOST</span>':''}${p.id===state.myId&&state.role!=='local'?'<span class="you-badge">YOU</span>':''}${state.role==='local'?`<button class="player-remove" data-remove="${p.id}">Remove</button>`:''}</div></div>`).join('');if(state.role==='local')$$('[data-remove]').forEach(b=>b.onclick=()=>removeLocalPlayer(b.dataset.remove))}
function renderFromSnapshot(){if(!state.game)return;if(state.game.phase==='lobby'){renderLobby();switchView('#lobbyView')}else if(state.game.phase==='playing'||state.game.phase==='roundResult'){renderGame()}else if(state.game.phase==='finished')renderResults()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$('#modeTabs').onclick=e=>{if(!e.target.dataset.mode)return;state.mode=e.target.dataset.mode;$$('#modeTabs button').forEach(b=>b.classList.toggle('selected',b===e.target));$$('.mode-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===state.mode))};
async function loadArtist(){const artist=$('#artistInput').value.trim();if(!artist)return setStatus('Enter an artist.','error');setStatus(`Loading ${artist} songs…`);try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(artist)}&entity=song&attribute=artistTerm&limit=50&country=AU`),d=await r.json();state.pool=d.results.filter(x=>x.artistName.toLowerCase().includes(artist.toLowerCase())).map(x=>({id:String(x.trackId),title:x.trackName,subtitle:x.artistName,art:(x.artworkUrl100||'').replace('100x100','600x600'),preview:x.previewUrl||''}));setStatus(`${state.pool.length} songs loaded.`,'ok')}catch(e){setStatus('Could not load songs.','error')}}
function spotifyPlaylistId(v){return v.match(/playlist[/:]([A-Za-z0-9]+)/)?.[1]||null}
function preparePool(){if(state.mode==='games')state.pool=gameCatalog;if(state.mode==='custom')state.pool=$('#customItems').value.split('\n').map(x=>x.trim()).filter(Boolean).map((title,i)=>({id:'c'+i,title,subtitle:$('#customCategory').value||'Custom draft',art:'',preview:''}))}
async function startGame(){preparePool();if(state.mode==='artist'&&!state.pool.length)await loadArtist();const rounds=Math.max(3,Math.min(20,+$('#rounds').value||5)),budget=Math.max(5,Math.min(100,+$('#budget').value||20));if(state.game.players.length<2)return setStatus('At least two players must join.','error');if(state.pool.length<rounds)return setStatus(`You need ${rounds} items, but only ${state.pool.length} are loaded.`,'error');const category=state.mode==='artist'?`${$('#artistInput').value} songs`:state.mode==='games'?$('#gameTheme').value||'Video games':state.mode==='custom'?$('#customCategory').value||'Custom draft':'Playlist draft';state.game.settings={rounds,budget,category,mode:state.mode};state.game.players.forEach(p=>{p.money=budget;p.picks=[]});state.game.queue=shuffle(state.pool).slice(0,rounds);state.game.round=0;state.game.bids={};state.game.roundResult=null;state.game.phase='playing';state.localBidIndex=0;broadcast();renderGame();if(state.role==='local')showPassDialog()}
function renderGame(){const g=state.game,item=g.queue[g.round];$('#gameRoomCode').textContent=state.roomCode;$('#gameRoomBadge').style.display=state.role==='local'?'none':'';$('#roundNumber').textContent=g.round+1;$('#roundTotal').textContent=g.settings.rounds;$('#categoryLabel').textContent=g.settings.category.toUpperCase();$('#itemMeta').textContent=`PICK ${g.round+1}`;$('#itemTitle').textContent=item.title;$('#itemSubtitle').textContent=item.subtitle;$('#itemArt').src=item.art||placeholder(item.title);$('#previewAudio').src=item.preview||'';$('#previewBtn').style.display=item.preview?'inline-block':'none';$('#scoreboard').innerHTML=g.players.map(p=>`<div class="player-score ${(state.role==='local'?p.id===currentLocalPlayer()?.id:p.id===state.myId)?'me':''} ${(g.locked||Object.keys(g.bids||{})).includes(p.id)?'locked':''}"><div><small>${escapeHtml(p.name.toUpperCase())}</small><strong>$${p.money}</strong><div class="pick-count">${p.picks.length} pick${p.picks.length===1?'':'s'}</div></div><div class="picks">${p.picks.slice(-4).map(x=>`<span class="pick-dot" title="${escapeHtml(x.title)}" style="background-image:url('${x.art||placeholder(x.title)}')"></span>`).join('')}</div></div>`).join('');const me=myPlayer(),activeId=state.role==='local'?me?.id:state.myId,locked=(g.locked||Object.keys(g.bids||{})).includes(activeId);$('#bidInput').max=me?.money||0;$('#bidInput').value=Math.min(+$('#bidInput').value||1,me?.money||0);$('.auction-panel').classList.toggle('locked',locked||g.phase==='roundResult');$('#bidPrompt').textContent=state.role==='local'&&me?`${me.name}, enter your secret bid`:'Enter your secret bid';$('#bidStatus').textContent=state.role==='local'?'Your bid will be hidden before the device is passed on.':locked?'Bid locked. Waiting for the other players…':'Your bid stays hidden until everybody has locked in.';$('#roundResult').hidden=g.phase!=='roundResult';if(g.roundResult){$('#roundWinnerText').textContent=`${g.roundResult.winnerName} wins “${g.roundResult.item.title}” for $${g.roundResult.price}!`;$('#roundBidText').textContent=g.roundResult.bidSummary}switchView('#gameView')}
function submitBid(){if(state.role==='local')return localSubmitBid();const me=myPlayer();if(!me||state.game.phase!=='playing')return;const bid=Math.max(0,Math.min(me.money,+$('#bidInput').value||0));if(state.role==='host')hostReceiveBid(state.myId,bid);else sendToHost({type:'bid',playerId:state.myId,bid})}
function hostReceiveBid(id,bid){if(state.game.phase!=='playing'||state.game.bids[id]!==undefined)return;const p=state.game.players.find(x=>x.id===id);if(!p)return;state.game.bids[id]=Math.max(0,Math.min(p.money,+bid||0));broadcast();renderGame();checkAllBids()}
function checkAllBids(){const active=state.game.players.filter(p=>p.connected!==false);if(active.every(p=>state.game.bids[p.id]!==undefined))resolveRound()}
function resolveRound(){const entries=state.game.players.map(p=>({p,bid:state.game.bids[p.id]??0})),max=Math.max(...entries.map(x=>x.bid)),tied=entries.filter(x=>x.bid===max),winner=tied[Math.floor(Math.random()*tied.length)],item=state.game.queue[state.game.round];winner.p.money-=winner.bid;winner.p.picks.push({...item,price:winner.bid});state.game.roundResult={winnerId:winner.p.id,winnerName:winner.p.name,price:winner.bid,item,bidSummary:entries.map(x=>`${x.p.name}: $${x.bid}`).join(' • ')};state.game.phase='roundResult';broadcast();renderGame()}
function nextRound(){if(state.role!=='host'&&state.role!=='local')return;state.game.round++;state.game.bids={};state.game.roundResult=null;state.localBidIndex=0;if(state.game.round>=state.game.settings.rounds){state.game.phase='finished'}else state.game.phase='playing';broadcast();renderFromSnapshot();if(state.role==='local'&&state.game.phase==='playing')showPassDialog()}
function renderResults(){const g=state.game,maxPicks=Math.max(...g.players.map(p=>p.picks.length)),leaders=g.players.filter(p=>p.picks.length===maxPicks);$('#winnerText').textContent=leaders.length===1?`${leaders[0].name} wins the draft!`:'Draft complete!';$('#winnerSub').textContent=g.players.map(p=>`${p.name}: ${p.picks.length} picks`).join(' • ');$('#finalBoard').innerHTML=g.players.map(p=>`<article class="final-player"><h2>${escapeHtml(p.name)} <small>— $${p.money} left</small></h2>${p.picks.length?p.picks.map(x=>`<div class="final-item"><img src="${x.art||placeholder(x.title)}"><div><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.subtitle)} • $${x.price}</small></div></div>`).join(''):'<p>No picks won.</p>'}</article>`).join('');switchView('#resultView')}
function backToLobby(){if(state.role!=='host'&&state.role!=='local')return;state.game.phase='lobby';state.game.queue=[];state.game.round=0;state.game.bids={};state.game.roundResult=null;broadcast();renderLobby();switchView('#lobbyView')}

$('#passPlayBtn').onclick=startPassPlay;$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#leaveRoomBtn').onclick=leaveRoom;$('#addLocalPlayerBtn').onclick=addLocalPlayer;$('#localPlayerName').onkeydown=e=>{if(e.key==='Enter')addLocalPlayer()};$('#passReadyBtn').onclick=()=>$('#passDialog').close();$('#copyRoomCode').onclick=async()=>{await navigator.clipboard.writeText(state.roomCode);$('#copyRoomCode').textContent='COPIED!';setTimeout(()=>$('#copyRoomCode').textContent=state.roomCode,1000)};$('#artistSearchBtn').onclick=loadArtist;$('#startBtn').onclick=startGame;$('#lockBidBtn').onclick=submitBid;$('#nextRoundBtn').onclick=nextRound;$('#playAgainBtn').onclick=backToLobby;
$$('.bid-controls button').forEach(b=>b.onclick=()=>{const i=$('#bidInput'),d=b.classList.contains('plus')?1:-1;i.value=Math.max(0,Math.min(+i.max,+i.value+d))});
$('#spotifyConnectBtn').onclick=connectSpotify;$('#spotifyDisconnectBtn').onclick=clearSpotifyTokens;$('#playlistLoadBtn').onclick=async()=>{const id=spotifyPlaylistId($('#playlistUrl').value.trim());if(!id)return setStatus('Paste a valid Spotify playlist URL.','error');setStatus('Importing playlist…');try{const token=await spotifyAccessToken();let url=`https://api.spotify.com/v1/playlists/${id}/items?limit=50&additional_types=track`,items=[];while(url){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw Error(d?.error?.message||'Spotify import failed');items.push(...d.items);url=d.next}state.pool=items.map(x=>x.item||x.track).filter(t=>t?.type==='track').map(t=>({id:t.id,title:t.name,subtitle:t.artists.map(a=>a.name).join(', '),art:t.album?.images?.[0]?.url||'',preview:t.preview_url||''}));setStatus(`${state.pool.length} tracks imported.`,'ok')}catch(e){setStatus(e.message,'error')}};
$('#textPlaylistBtn').onclick=()=>{const lines=$('#playlistText').value.split('\n').map(x=>x.trim()).filter(Boolean);state.pool=lines.map((line,i)=>{const [title,...r]=line.split(/\s+[—–-]\s+/);return{id:'t'+i,title,subtitle:r.join(' — ')||'Playlist item',art:'',preview:''}});setStatus(`${state.pool.length} items ready.`,'ok')};
$('#previewBtn').onclick=()=>{const a=$('#previewAudio');if(a.paused){a.play();$('#previewBtn').textContent='❚❚ Pause preview'}else{a.pause();$('#previewBtn').textContent='▶ Play preview'}};$('#soundBtn').onclick=()=>{const a=$('#previewAudio');a.muted=!a.muted;$('#soundBtn').textContent=a.muted?'🔇 Sound off':'🔊 Sound on'};$('#howBtn').onclick=()=>$('#howDialog').showModal();$('#closeHow').onclick=()=>$('#howDialog').close();$('#joinCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'');

(async function init(){const id=localStorage.getItem('draftDuelSpotifyClientId')||'';$('#spotifyClientId').value=id;$('#spotifyRedirectUri').textContent=spotifyRedirectUri();updateSpotifyUi();await handleSpotifyCallback()})();
